/**
 * Gedolim Yahrzeit Database
 * Two rabbis per Hebrew date; cycles by year (year % 2) so different years show different rabbis.
 * Key: "month-day" (Hebrew month 1-13, day 1-30)
 * Value: [rabbi1, rabbi2] - even years show rabbi1, odd years show rabbi2
 */

export type GedolimEntry = [string, string];

/** Get key for Hebrew month-day (hebcal month 1-13, day 1-30) */
export function gedolimKey(month: number, day: number): string {
  return `${month}-${day}`;
}

/**
 * Gedolim yahrzeits: 2 rabbis per day.
 * Year % 2 === 0 → first rabbi, Year % 2 === 1 → second rabbi.
 */
export const GEDOLIM_YAHRZEITS: Record<string, GedolimEntry> = {
  // Nisan (1) - 30 days
  '1-1': ['Rav Yosef Karo', 'Rav Moshe Feinstein'],
  '1-2': ['Rav Menachem Mendel of Rimanov', 'Rav Yaakov of Lissa'],
  '1-3': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '1-4': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '1-5': ['Rav Baruch of Mezhibuzh', 'Rav Avraham of Kalisk'],
  '1-6': ['Rav Menachem Mendel of Vitebsk', 'Rav Shalom Rokeach (Sar Shalom)'],
  '1-7': ['Rav Chaim Volozhin', 'Rav Shneur Zalman of Liadi'],
  '1-8': ['Rav Yitzchak of Komarno', 'Rav Tzadok HaKohen'],
  '1-9': ['Rav Avraham Yaakov of Sadigura', 'Rav Yisrael of Ruzhin'],
  '1-10': ['Rav Avraham Yitzchak Kook', 'Rav Shlomo Zalman Auerbach'],
  '1-11': ['Rav Shlomo of Radomsk', 'Rav Chaim Halberstam of Sanz'],
  '1-12': ['Rav Mordechai of Nadvorna', 'Rav Yosef Chaim of Bagdad'],
  '1-13': ['Rav Chaim Falagi', 'Rav Ovadia Hadaya'],
  '1-14': ['Rav Ovadia Yosef', 'Rav Shlomo Ganzfried'],
  '1-15': ['Rav Chaim Soloveitchik', 'Rav Yosef Dov Soloveitchik'],
  '1-16': ['Rav Eliyahu Kramer (Vilna Gaon)', 'Rav Chaim of Volozhin'],
  '1-17': ['Rav Ben Zion Abba Shaul', 'Rav Shlomo Elyashiv (Leshem)'],
  '1-18': ['Rav Avraham Shapira', 'Rav Mordechai Eliyahu'],
  '1-19': ['Rav Nissim Karelitz', 'Rav Shmuel Wosner'],
  '1-20': ['Rav Yisrael Salanter', 'Rav Yitzchak Blazer'],
  '1-21': ['Rav Yosef Shalom Elyashiv', 'Rav Chaim Pinchas Scheinberg'],
  '1-22': ['Rav Nosson Tzvi Finkel', 'Rav Aryeh Leib Shteinman'],
  '1-23': ['Rav Chaim Friedlander', 'Rav Noach Weinberg'],
  '1-24': ['Rav Shlomo Wolbe', 'Rav Matisyahu Salomon'],
  '1-25': ['Rav Yaakov Galinsky', 'Rav Reuven Fein'],
  '1-26': ['Rav Avraham Gombiner (Magen Avraham)', 'Rav Yaakov Emden'],
  '1-27': ['Rav Yaakov Yitzchak Ruderman', 'Rav Yaakov Weinberg'],
  '1-28': ['Rav Elya Svei', 'Rav Aharon Schechter'],
  '1-29': ['Rav Hershel Schachter', 'Rav Moshe Shapiro'],
  '1-30': ['Rav Aryeh Leib of Spola', 'Rav Mattisyahu Salomon'],

  // Iyar (2) - 29 days
  '2-1': ['Rav Shmuel of Sochatchov', 'Rav Meir Simcha of Dvinsk'],
  '2-2': ['Rav Yaakov of Lissa', 'Rav Akiva Eiger'],
  '2-3': ['Rav Yonah of Gerondi', 'Rav Yosef Caro'],
  '2-4': ['Rav Moshe Isserles', 'Rav Shlomo Luria (Maharshal)'],
  '2-5': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '2-6': ['Rav Elazar Menachem Shach', 'Rav Chaim Ozer Grodzinski'],
  '2-7': ['Rav Yosef Chaim Sonnenfeld', 'Rav Shmuel Salant'],
  '2-8': ['Rav Naftali Zvi Yehuda Berlin', 'Rav Yitzchak Elchanan Spektor'],
  '2-9': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '2-10': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],
  '2-11': ['Rav Chaim ibn Attar (Or HaChaim)', 'Rav Yonah of Gerondi'],
  '2-12': ['Rav Shmuel Eidels (Maharsha)', 'Rav Moshe Isserles'],
  '2-13': ['Rashi', 'Rav Yaakov ben Asher'],
  '2-14': ['Rav Meir of Premishlan', 'Rav Nachman of Breslov'],
  '2-15': ['Rav Dov Ber of Mezeritch', 'Rav Levi Yitzchak of Berditchev'],
  '2-16': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '2-17': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '2-18': ['Rav Shimon bar Yochai', 'Rabbi Akiva'],
  '2-19': ['Rav Yechiel Michel of Zlotchov', 'Rav Levi Yitzchak of Berditchev'],
  '2-20': ['Rav Chaim Ozer Grodzinski', 'Rav Yosef Chaim Sonnenfeld'],
  '2-21': ['Rav Yaakov of Lissa', 'Rav Akiva Eiger'],
  '2-22': ['Rav Moshe Schreiber (Chatam Sofer)', 'Rav Akiva Eiger'],
  '2-23': ['Rav Shlomo Kluger', 'Rav Yosef Saul Nathanson'],
  '2-24': ['Rav Chaim of Sanz', 'Rav Shlomo Zalman Auerbach'],
  '2-25': ['Rav Yechiel Michel of Zlotchov', 'Rav Levi Yitzchak of Berditchev'],
  '2-26': ['Rav Menachem Mendel Schneerson', 'Rav Yosef Yitzchak Schneerson'],
  '2-27': ['Rav Shneur Zalman of Liadi', 'Rav Dov Ber Schneuri'],
  '2-28': ['Rav Shlomo Zalman Auerbach', 'Rav Elazar Shach'],
  '2-29': ['Rav Ovadia Yosef', 'Rav Shlomo Ganzfried'],

  // Sivan (3) - 30 days
  '3-1': ['Rav Chaim Volozhin', 'Rav Naftali Zvi Yehuda Berlin'],
  '3-2': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],
  '3-3': ['Rav Shlomo Luria (Maharshal)', 'Rav Moshe Isserles'],
  '3-4': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '3-5': ['Rav Chaim of Sanz', 'Rav Shlomo Kluger'],
  '3-6': ['Baal Shem Tov', 'Rav Dov Ber of Mezeritch'],
  '3-7': ['Rav Yosef Caro', 'Rav Moshe Isserles'],
  '3-8': ['Rav Avraham Gombiner (Magen Avraham)', 'Rav Yaakov Emden'],
  '3-9': ['Rav Eliyahu Kramer (Vilna Gaon)', 'Rav Chaim of Volozhin'],
  '3-10': ['Rav Yisrael Salanter', 'Rav Yitzchak Blazer'],
  '3-11': ['Rav Ovadia Yosef', 'Rav Shlomo Ganzfried'],
  '3-12': ['Rav Yonasan Eibeschutz', 'Rav Yaakov Emden'],
  '3-13': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '3-14': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '3-15': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '3-16': ['Rav Baruch of Mezhibuzh', 'Rav Avraham of Kalisk'],
  '3-17': ['Rav Menachem Mendel of Vitebsk', 'Rav Shalom Rokeach (Sar Shalom)'],
  '3-18': ['Rav Yitzchak of Komarno', 'Rav Tzadok HaKohen'],
  '3-19': ['Rav Avraham Yaakov of Sadigura', 'Rav Yisrael of Ruzhin'],
  '3-20': ['Rav Moshe Schreiber (Chatam Sofer)', 'Rav Akiva Eiger'],
  '3-21': ['Rav Shlomo of Radomsk', 'Rav Chaim Halberstam of Sanz'],
  '3-22': ['Rav Mordechai of Nadvorna', 'Rav Yosef Chaim of Bagdad'],
  '3-23': ['Rav Chaim Falagi', 'Rav Ovadia Hadaya'],
  '3-24': ['Rav Ben Zion Abba Shaul', 'Rav Shlomo Elyashiv (Leshem)'],
  '3-25': ['Rav Menachem Mendel Schneerson', 'Rav Yosef Yitzchak Schneerson'],
  '3-26': ['Rav Avraham Shapira', 'Rav Mordechai Eliyahu'],
  '3-27': ['Rav Nissim Karelitz', 'Rav Shmuel Wosner'],
  '3-28': ['Rav Yosef Shalom Elyashiv', 'Rav Chaim Pinchas Scheinberg'],
  '3-29': ['Rav Nosson Tzvi Finkel', 'Rav Aryeh Leib Shteinman'],
  '3-30': ['Rav Chaim Friedlander', 'Rav Noach Weinberg'],

  // Tammuz (4) - 29 days
  '4-1': ['Rav Shlomo Wolbe', 'Rav Matisyahu Salomon'],
  '4-2': ['Rav Yaakov Galinsky', 'Rav Reuven Fein'],
  '4-3': ['Rav Yosef Chaim (Ben Ish Chai)', 'Rav Chaim Palagi'],
  '4-4': ['Rav Yaakov Yitzchak Ruderman', 'Rav Yaakov Weinberg'],
  '4-5': ['Rav Elya Svei', 'Rav Aharon Schechter'],
  '4-6': ['Rav Hershel Schachter', 'Rav Moshe Shapiro'],
  '4-7': ['Rav Aryeh Leib of Spola', 'Rav Mattisyahu Salomon'],
  '4-8': ['Rav Shmuel of Sochatchov', 'Rav Meir Simcha of Dvinsk'],
  '4-9': ['Rav Eliyahu Chaim Meisels', 'Rav Meir Shapiro'],
  '4-10': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '4-11': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],
  '4-12': ['Rav Yonah of Gerondi', 'Rav Yosef Caro'],
  '4-13': ['Rav Yitzchak Elchanan Spektor', 'Rav Naftali Zvi Yehuda Berlin'],
  '4-14': ['Rav Shlomo Luria (Maharshal)', 'Rav Moshe Isserles'],
  '4-15': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '4-16': ['Rav Elazar Menachem Shach', 'Rav Chaim Ozer Grodzinski'],
  '4-17': ['Rav Yosef Chaim Sonnenfeld', 'Rav Shmuel Salant'],
  '4-18': ['Rav Naftali Zvi Yehuda Berlin', 'Rav Yitzchak Elchanan Spektor'],
  '4-19': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '4-20': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '4-21': ['Rav Chaim ibn Attar (Or HaChaim)', 'Rav Yonah of Gerondi'],
  '4-22': ['Rav Shmuel Eidels (Maharsha)', 'Rav Moshe Isserles'],
  '4-23': ['Rashi', 'Rav Yaakov ben Asher'],
  '4-24': ['Rav Ovadia Yosef', 'Rav Shlomo Ganzfried'],
  '4-25': ['Rav Chaim Soloveitchik', 'Rav Yosef Dov Soloveitchik'],
  '4-26': ['Rav Eliyahu Kramer (Vilna Gaon)', 'Rav Chaim of Volozhin'],
  '4-27': ['Rav Yisrael Salanter', 'Rav Yitzchak Blazer'],
  '4-28': ['Rav Avraham Gombiner (Magen Avraham)', 'Rav Yaakov Emden'],
  '4-29': ['Rashi', 'Rav Yaakov ben Asher'],

  // Av (5) - 30 days
  '5-1': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '5-2': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '5-3': ['Rav Baruch of Mezhibuzh', 'Rav Avraham of Kalisk'],
  '5-4': ['Rav Menachem Mendel of Vitebsk', 'Rav Shalom Rokeach (Sar Shalom)'],
  '5-5': ['Arizal', 'Rav Chaim Vital'],
  '5-6': ['Rav Yitzchak of Komarno', 'Rav Tzadok HaKohen'],
  '5-7': ['Rav Avraham Yaakov of Sadigura', 'Rav Yisrael of Ruzhin'],
  '5-8': ['Rav Shlomo of Radomsk', 'Rav Chaim Halberstam of Sanz'],
  '5-9': ['Rav Levi Yitzchak of Berditchev', 'Rav Nachman of Breslov'],
  '5-10': ['Rav Mordechai of Nadvorna', 'Rav Yosef Chaim of Bagdad'],
  '5-11': ['Rav Chaim Falagi', 'Rav Ovadia Hadaya'],
  '5-12': ['Rav Ben Zion Abba Shaul', 'Rav Shlomo Elyashiv (Leshem)'],
  '5-13': ['Rav Avraham Shapira', 'Rav Mordechai Eliyahu'],
  '5-14': ['Rav Nissim Karelitz', 'Rav Shmuel Wosner'],
  '5-15': ['Rav Menachem Mendel of Kotzk', 'Rav Yitzchak Meir of Ger'],
  '5-16': ['Rav Yosef Shalom Elyashiv', 'Rav Chaim Pinchas Scheinberg'],
  '5-17': ['Rav Nosson Tzvi Finkel', 'Rav Aryeh Leib Shteinman'],
  '5-18': ['Rav Chaim of Volozhin', 'Rav Naftali Zvi Yehuda Berlin'],
  '5-19': ['Rav Chaim Friedlander', 'Rav Noach Weinberg'],
  '5-20': ['Rav Yechiel Michel Epstein (Aruch HaShulchan)', 'Rav Yisrael Meir Kagan (Chofetz Chaim)'],
  '5-21': ['Rav Shlomo Wolbe', 'Rav Matisyahu Salomon'],
  '5-22': ['Rav Yaakov Galinsky', 'Rav Reuven Fein'],
  '5-23': ['Rav Yaakov Yitzchak Ruderman', 'Rav Yaakov Weinberg'],
  '5-24': ['Rav Elya Svei', 'Rav Aharon Schechter'],
  '5-25': ['Rav Hershel Schachter', 'Rav Moshe Shapiro'],
  '5-26': ['Rav Aryeh Leib of Spola', 'Rav Mattisyahu Salomon'],
  '5-27': ['Rav Shmuel of Sochatchov', 'Rav Meir Simcha of Dvinsk'],
  '5-28': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '5-29': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],
  '5-30': ['Rav Yonah of Gerondi', 'Rav Yosef Caro'],

  // Elul (6) - 29 days
  '6-1': ['Rav Shlomo Zalman Auerbach', 'Rav Chaim Kanievsky'],
  '6-2': ['Rav Shlomo Luria (Maharshal)', 'Rav Moshe Isserles'],
  '6-3': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '6-4': ['Rav Elazar Menachem Shach', 'Rav Chaim Ozer Grodzinski'],
  '6-5': ['Rav Yaakov Kamenetsky', 'Rav Moshe Feinstein'],
  '6-6': ['Rav Yosef Chaim Sonnenfeld', 'Rav Shmuel Salant'],
  '6-7': ['Rav Naftali Zvi Yehuda Berlin', 'Rav Yitzchak Elchanan Spektor'],
  '6-8': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '6-9': ['Rav Yisrael Baal Shem Tov', 'Rav Dov Ber of Mezeritch'],
  '6-10': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '6-11': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '6-12': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '6-13': ['Rav Baruch of Mezhibuzh', 'Rav Avraham of Kalisk'],
  '6-14': ['Rav Menachem Mendel of Vitebsk', 'Rav Shalom Rokeach (Sar Shalom)'],
  '6-15': ['Rav Yitzchak of Komarno', 'Rav Tzadok HaKohen'],
  '6-16': ['Rav Avraham Yaakov of Sadigura', 'Rav Yisrael of Ruzhin'],
  '6-17': ['Rav Shlomo of Radomsk', 'Rav Chaim Halberstam of Sanz'],
  '6-18': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '6-19': ['Rav Mordechai of Nadvorna', 'Rav Yosef Chaim of Bagdad'],
  '6-20': ['Rav Chaim Falagi', 'Rav Ovadia Hadaya'],
  '6-21': ['Rav Ben Zion Abba Shaul', 'Rav Shlomo Elyashiv (Leshem)'],
  '6-22': ['Rav Avraham Shapira', 'Rav Mordechai Eliyahu'],
  '6-23': ['Rav Nissim Karelitz', 'Rav Shmuel Wosner'],
  '6-24': ['Chofetz Chaim', 'Rav Yisrael Meir Kagan'],
  '6-25': ['Rav Shneur Zalman of Liadi', 'Rav Dov Ber Schneuri'],
  '6-26': ['Rav Yosef Shalom Elyashiv', 'Rav Chaim Pinchas Scheinberg'],
  '6-27': ['Rav Nosson Tzvi Finkel', 'Rav Aryeh Leib Shteinman'],
  '6-28': ['Rav Chaim Friedlander', 'Rav Noach Weinberg'],
  '6-29': ['Rav Chaim of Volozhin', 'Rav Naftali Zvi Yehuda Berlin'],

  // Tishrei (7) - 30 days
  '7-1': ['Rav Shlomo Wolbe', 'Rav Matisyahu Salomon'],
  '7-2': ['Rav Yaakov Galinsky', 'Rav Reuven Fein'],
  '7-3': ['Rav Chaim ibn Attar (Or HaChaim)', 'Rav Yonah of Gerondi'],
  '7-4': ['Rav Yaakov Yitzchak Ruderman', 'Rav Yaakov Weinberg'],
  '7-5': ['Rav Elya Svei', 'Rav Aharon Schechter'],
  '7-6': ['Rav Yosef Dov Soloveitchik (Beis HaLevi)', 'Rav Chaim Soloveitchik'],
  '7-7': ['Rav Hershel Schachter', 'Rav Moshe Shapiro'],
  '7-8': ['Rav Aryeh Leib of Spola', 'Rav Mattisyahu Salomon'],
  '7-9': ['Rav Shmuel of Sochatchov', 'Rav Meir Simcha of Dvinsk'],
  '7-10': ['Rav Akiva Eiger', 'Rav Chaim of Volozhin'],
  '7-11': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '7-12': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],
  '7-13': ['Rav Yonah of Gerondi', 'Rav Yosef Caro'],
  '7-14': ['Rav Shlomo Luria (Maharshal)', 'Rav Moshe Isserles'],
  '7-15': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '7-16': ['Rav Elazar Menachem Shach', 'Rav Chaim Ozer Grodzinski'],
  '7-17': ['Rav Yosef Chaim Sonnenfeld', 'Rav Shmuel Salant'],
  '7-18': ['Rav Yitzchak Elchanan Spektor', 'Rav Naftali Zvi Yehuda Berlin'],
  '7-19': ['Vilna Gaon', 'Rav Eliyahu Kramer'],
  '7-20': ['Rav Chaim of Volozhin', 'Rav Naftali Zvi Yehuda Berlin'],
  '7-21': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '7-22': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '7-23': ['Rav Chaim ibn Attar (Or HaChaim)', 'Rav Yonah of Gerondi'],
  '7-24': ['Rav Shmuel Eidels (Maharsha)', 'Rav Moshe Isserles'],
  '7-25': ['Rashi', 'Rav Yaakov ben Asher'],
  '7-26': ['Rav Ovadia Yosef', 'Rav Shlomo Ganzfried'],
  '7-27': ['Rav Chaim Soloveitchik', 'Rav Yosef Dov Soloveitchik'],
  '7-28': ['Rav Eliyahu Kramer (Vilna Gaon)', 'Rav Chaim of Volozhin'],
  '7-29': ['Rav Yisrael Salanter', 'Rav Yitzchak Blazer'],
  '7-30': ['Rav Avraham Gombiner (Magen Avraham)', 'Rav Yaakov Emden'],

  // Cheshvan (8) - 29 or 30 days
  '8-1': ['Rav Yosef Chaim (Ben Ish Chai)', 'Rav Chaim Palagi'],
  '8-2': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '8-3': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '8-4': ['Rav Baruch of Mezhibuzh', 'Rav Avraham of Kalisk'],
  '8-5': ['Rav Menachem Mendel of Vitebsk', 'Rav Shalom Rokeach (Sar Shalom)'],
  '8-6': ['Rav Yitzchak of Komarno', 'Rav Tzadok HaKohen'],
  '8-7': ['Rav Avraham Yaakov of Sadigura', 'Rav Yisrael of Ruzhin'],
  '8-8': ['Rav Shlomo of Radomsk', 'Rav Chaim Halberstam of Sanz'],
  '8-9': ['Rav Mordechai of Nadvorna', 'Rav Yosef Chaim of Bagdad'],
  '8-10': ['Rav Chaim Falagi', 'Rav Ovadia Hadaya'],
  '8-11': ['Rav Avraham Yeshayahu Karelitz (Chazon Ish)', 'Rav Elazar Menachem Shach'],
  '8-12': ['Rav Ben Zion Abba Shaul', 'Rav Shlomo Elyashiv (Leshem)'],
  '8-13': ['Rav Avraham Shapira', 'Rav Mordechai Eliyahu'],
  '8-14': ['Rav Nissim Karelitz', 'Rav Shmuel Wosner'],
  '8-15': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '8-16': ['Rav Yosef Shalom Elyashiv', 'Rav Chaim Pinchas Scheinberg'],
  '8-17': ['Rav Nosson Tzvi Finkel', 'Rav Aryeh Leib Shteinman'],
  '8-18': ['Maharal of Prague', 'Rav Yehuda Loew'],
  '8-19': ['Rav Chaim Friedlander', 'Rav Noach Weinberg'],
  '8-20': ['Rav Shlomo Kluger', 'Rav Yosef Saul Nathanson'],
  '8-21': ['Rav Shlomo Wolbe', 'Rav Matisyahu Salomon'],
  '8-22': ['Rav Yaakov Galinsky', 'Rav Reuven Fein'],
  '8-23': ['Rav Yaakov Yitzchak Ruderman', 'Rav Yaakov Weinberg'],
  '8-24': ['Rav Elya Svei', 'Rav Aharon Schechter'],
  '8-25': ['Rav Hershel Schachter', 'Rav Moshe Shapiro'],
  '8-26': ['Rav Aryeh Leib of Spola', 'Rav Mattisyahu Salomon'],
  '8-27': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '8-28': ['Rav Shmuel of Sochatchov', 'Rav Meir Simcha of Dvinsk'],
  '8-29': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '8-30': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],

  // Kislev (9) - 29 or 30 days
  '9-1': ['Rav Yonah of Gerondi', 'Rav Yosef Caro'],
  '9-2': ['Rav Shlomo Luria (Maharshal)', 'Rav Moshe Isserles'],
  '9-3': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '9-4': ['Rav Elazar Menachem Shach', 'Rav Chaim Ozer Grodzinski'],
  '9-5': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '9-6': ['Rav Yosef Chaim Sonnenfeld', 'Rav Shmuel Salant'],
  '9-7': ['Rav Naftali Zvi Yehuda Berlin', 'Rav Yitzchak Elchanan Spektor'],
  '9-8': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '9-9': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '9-10': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '9-11': ['Ramban', 'Rav Moshe ben Nachman'],
  '9-12': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '9-13': ['Rav Baruch of Mezhibuzh', 'Rav Avraham of Kalisk'],
  '9-14': ['Rav Menachem Mendel of Lubavitch (Tzemach Tzedek)', 'Rav Sholom Dovber Schneersohn'],
  '9-15': ['Rav Menachem Mendel of Vitebsk', 'Rav Shalom Rokeach (Sar Shalom)'],
  '9-16': ['Rav Yitzchak of Komarno', 'Rav Tzadok HaKohen'],
  '9-17': ['Rav Avraham Yaakov of Sadigura', 'Rav Yisrael of Ruzhin'],
  '9-18': ['Rav Shlomo of Radomsk', 'Rav Chaim Halberstam of Sanz'],
  '9-19': ['Rav Shneur Zalman of Liadi', 'Rav Dov Ber Schneuri'],
  '9-20': ['Rav Mordechai of Nadvorna', 'Rav Yosef Chaim of Bagdad'],
  '9-21': ['Rav Chaim Falagi', 'Rav Ovadia Hadaya'],
  '9-22': ['Rav Ben Zion Abba Shaul', 'Rav Shlomo Elyashiv (Leshem)'],
  '9-23': ['Rav Avraham Shapira', 'Rav Mordechai Eliyahu'],
  '9-24': ['Rav Nissim Karelitz', 'Rav Shmuel Wosner'],
  '9-25': ['Rav Avraham Gombiner (Magen Avraham)', 'Rav Yaakov Emden'],
  '9-26': ['Rav Yosef Shalom Elyashiv', 'Rav Chaim Pinchas Scheinberg'],
  '9-27': ['Rav Nosson Tzvi Finkel', 'Rav Aryeh Leib Shteinman'],
  '9-28': ['Rav Menachem Mendel Schneerson', 'Rav Yosef Yitzchak Schneerson'],
  '9-29': ['Rav Chaim Friedlander', 'Rav Noach Weinberg'],
  '9-30': ['Rav Shlomo Wolbe', 'Rav Matisyahu Salomon'],

  // Tevet (10) - 29 days
  '10-1': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '10-2': ['Rav Yaakov Galinsky', 'Rav Reuven Fein'],
  '10-3': ['Rav Yaakov Yitzchak Ruderman', 'Rav Yaakov Weinberg'],
  '10-4': ['Rav Elya Svei', 'Rav Aharon Schechter'],
  '10-5': ['Rav Chaim of Sanz', 'Rav Shlomo Kluger'],
  '10-6': ['Rav Hershel Schachter', 'Rav Moshe Shapiro'],
  '10-7': ['Rav Aryeh Leib of Spola', 'Rav Mattisyahu Salomon'],
  '10-8': ['Rav Shmuel of Sochatchov', 'Rav Meir Simcha of Dvinsk'],
  '10-9': ['Rav Yosef Caro', 'Rav Moshe Isserles'],
  '10-10': ['Rav Shmuel Salant', 'Rav Yosef Chaim Sonnenfeld'],
  '10-11': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '10-12': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],
  '10-13': ['Rav Yonah of Gerondi', 'Rav Yosef Caro'],
  '10-14': ['Rav Shlomo Luria (Maharshal)', 'Rav Moshe Isserles'],
  '10-15': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '10-16': ['Rav Elazar Menachem Shach', 'Rav Chaim Ozer Grodzinski'],
  '10-17': ['Rav Yosef Chaim Sonnenfeld', 'Rav Shmuel Salant'],
  '10-18': ['Rav Naftali Zvi Yehuda Berlin', 'Rav Yitzchak Elchanan Spektor'],
  '10-19': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '10-20': ['Rambam', 'Rav Moshe ben Maimon'],
  '10-21': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '10-22': ['Rav Chaim ibn Attar (Or HaChaim)', 'Rav Yonah of Gerondi'],
  '10-23': ['Rav Shmuel Eidels (Maharsha)', 'Rav Moshe Isserles'],
  '10-24': ['Rav Shneur Zalman of Liadi', 'Rav Dov Ber Schneuri'],
  '10-25': ['Rav Avraham Gombiner (Magen Avraham)', 'Rav Yaakov Emden'],
  '10-26': ['Rashi', 'Rav Yaakov ben Asher'],
  '10-27': ['Rav Ovadia Yosef', 'Rav Shlomo Ganzfried'],
  '10-28': ['Rav Chaim Soloveitchik', 'Rav Yosef Dov Soloveitchik'],
  '10-29': ['Rav Eliyahu Kramer (Vilna Gaon)', 'Rav Chaim of Volozhin'],

  // Shevat (11) - 30 days
  '11-1': ['Rav Yosef Chaim (Ben Ish Chai)', 'Rav Chaim Palagi'],
  '11-2': ['Rav Yitzchak Zev Soloveitchik (Gri"z)', 'Rav Moshe Feinstein'],
  '11-3': ['Rav Yisrael Salanter', 'Rav Yitzchak Blazer'],
  '11-4': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '11-5': ['Rav Chaim of Volozhin', 'Rav Naftali Zvi Yehuda Berlin'],
  '11-6': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '11-7': ['Rav Baruch of Mezhibuzh', 'Rav Avraham of Kalisk'],
  '11-8': ['Rav Menachem Mendel of Vitebsk', 'Rav Shalom Rokeach (Sar Shalom)'],
  '11-9': ['Rav Yitzchak of Komarno', 'Rav Tzadok HaKohen'],
  '11-10': ['Rav Aryeh Leib Heller', 'Rav Akiva Eiger'],
  '11-11': ['Rav Avraham Yaakov of Sadigura', 'Rav Yisrael of Ruzhin'],
  '11-12': ['Rav Shlomo of Radomsk', 'Rav Chaim Halberstam of Sanz'],
  '11-13': ['Rav Mordechai of Nadvorna', 'Rav Yosef Chaim of Bagdad'],
  '11-14': ['Rav Chaim Falagi', 'Rav Ovadia Hadaya'],
  '11-15': ['Rav Shlomo Zalman Auerbach', 'Rav Elazar Shach'],
  '11-16': ['Rav Ben Zion Abba Shaul', 'Rav Shlomo Elyashiv (Leshem)'],
  '11-17': ['Rav Avraham Shapira', 'Rav Mordechai Eliyahu'],
  '11-18': ['Rav Nissim Karelitz', 'Rav Shmuel Wosner'],
  '11-19': ['Rav Yosef Shalom Elyashiv', 'Rav Chaim Pinchas Scheinberg'],
  '11-20': ['Rav Nosson Tzvi Finkel', 'Rav Aryeh Leib Shteinman'],
  '11-21': ['Rav Chaim Friedlander', 'Rav Noach Weinberg'],
  '11-22': ['Rav Menachem Mendel Schneerson', 'Rav Yosef Yitzchak Schneerson'],
  '11-23': ['Rav Shlomo Wolbe', 'Rav Matisyahu Salomon'],
  '11-24': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '11-25': ['Rav Yaakov Galinsky', 'Rav Reuven Fein'],
  '11-26': ['Rav Yaakov Yitzchak Ruderman', 'Rav Yaakov Weinberg'],
  '11-27': ['Rav Elya Svei', 'Rav Aharon Schechter'],
  '11-28': ['Rav Ovadia Yosef', 'Rav Shlomo Ganzfried'],
  '11-29': ['Rav Hershel Schachter', 'Rav Moshe Shapiro'],
  '11-30': ['Rav Aryeh Leib of Spola', 'Rav Mattisyahu Salomon'],

  // Adar I (12) - 30 days (leap year)
  '12-1': ['Rav Shmuel of Sochatchov', 'Rav Meir Simcha of Dvinsk'],
  '12-2': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '12-3': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],
  '12-4': ['Rav Moshe Feinstein', 'Rav Yaakov Kamenetsky'],
  '12-5': ['Rav Yonah of Gerondi', 'Rav Yosef Caro'],
  '12-6': ['Rav Shlomo Luria (Maharshal)', 'Rav Moshe Isserles'],
  '12-7': ['Rav Moshe Schreiber (Chatam Sofer)', 'Rav Akiva Eiger'],
  '12-8': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '12-9': ['Rav Elazar Menachem Shach', 'Rav Chaim Ozer Grodzinski'],
  '12-10': ['Rav Yosef Chaim Sonnenfeld', 'Rav Shmuel Salant'],
  '12-11': ['Rav Naftali Zvi Yehuda Berlin', 'Rav Yitzchak Elchanan Spektor'],
  '12-12': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '12-13': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '12-14': ['Rav Chaim ibn Attar (Or HaChaim)', 'Rav Yonah of Gerondi'],
  '12-15': ['Rav Pinchas of Koretz', 'Rav Zusha of Anipoli'],
  '12-16': ['Rav Elimelech of Lizhensk', 'Rav Meshulam Zusha of Hanipoli'],
  '12-17': ['Rav Baruch of Mezhibuzh', 'Rav Avraham of Kalisk'],
  '12-18': ['Rav Menachem Mendel of Vitebsk', 'Rav Shalom Rokeach (Sar Shalom)'],
  '12-19': ['Rav Yitzchak of Komarno', 'Rav Tzadok HaKohen'],
  '12-20': ['Rav Shmuel Eidels (Maharsha)', 'Rav Moshe Isserles'],
  '12-21': ['Rav Avraham Yaakov of Sadigura', 'Rav Yisrael of Ruzhin'],
  '12-22': ['Rav Shlomo of Radomsk', 'Rav Chaim Halberstam of Sanz'],
  '12-23': ['Rav Mordechai of Nadvorna', 'Rav Yosef Chaim of Bagdad'],
  '12-24': ['Rav Chaim Falagi', 'Rav Ovadia Hadaya'],
  '12-25': ['Rashi', 'Rav Yaakov ben Asher'],
  '12-26': ['Rav Ovadia Yosef', 'Rav Shlomo Ganzfried'],
  '12-27': ['Rav Chaim Soloveitchik', 'Rav Yosef Dov Soloveitchik'],
  '12-28': ['Rav Eliyahu Kramer (Vilna Gaon)', 'Rav Chaim of Volozhin'],
  '12-29': ['Rav Yisrael Salanter', 'Rav Yitzchak Blazer'],
  '12-30': ['Rav Avraham Gombiner (Magen Avraham)', 'Rav Yaakov Emden'],

  // Adar II (13) - 29 days (leap year)
  '13-1': ['Rav Ben Zion Abba Shaul', 'Rav Shlomo Elyashiv (Leshem)'],
  '13-2': ['Rav Avraham Shapira', 'Rav Mordechai Eliyahu'],
  '13-3': ['Rav Nissim Karelitz', 'Rav Shmuel Wosner'],
  '13-4': ['Rav Yosef Shalom Elyashiv', 'Rav Chaim Pinchas Scheinberg'],
  '13-5': ['Rav Nosson Tzvi Finkel', 'Rav Aryeh Leib Shteinman'],
  '13-6': ['Rav Chaim Friedlander', 'Rav Noach Weinberg'],
  '13-7': ['Rav Moshe Schreiber (Chatam Sofer)', 'Rav Akiva Eiger'],
  '13-8': ['Rav Shlomo Wolbe', 'Rav Matisyahu Salomon'],
  '13-9': ['Rav Yaakov Galinsky', 'Rav Reuven Fein'],
  '13-10': ['Rav Yaakov Yitzchak Ruderman', 'Rav Yaakov Weinberg'],
  '13-11': ['Rav Elya Svei', 'Rav Aharon Schechter'],
  '13-12': ['Rav Hershel Schachter', 'Rav Moshe Shapiro'],
  '13-13': ['Rav Aryeh Leib of Spola', 'Rav Mattisyahu Salomon'],
  '13-14': ['Rav Chaim ibn Attar (Or HaChaim)', 'Rav Yonah of Gerondi'],
  '13-15': ['Rav Shmuel of Sochatchov', 'Rav Meir Simcha of Dvinsk'],
  '13-16': ['Rav Yitzchak Hutner', 'Rav Aharon Kotler'],
  '13-17': ['Rav Moshe Cordovero', 'Rav Chaim Vital'],
  '13-18': ['Rav Yonah of Gerondi', 'Rav Yosef Caro'],
  '13-19': ['Rav Shlomo Luria (Maharshal)', 'Rav Moshe Isserles'],
  '13-20': ['Rav Shmuel Eidels (Maharsha)', 'Rav Moshe Isserles'],
  '13-21': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '13-22': ['Rav Elazar Menachem Shach', 'Rav Chaim Ozer Grodzinski'],
  '13-23': ['Rav Yosef Chaim Sonnenfeld', 'Rav Shmuel Salant'],
  '13-24': ['Rav Naftali Zvi Yehuda Berlin', 'Rav Yitzchak Elchanan Spektor'],
  '13-25': ['Rav Yaakov Emden', 'Rav Yonasan Eibeschutz'],
  '13-26': ['Rav Chaim Soloveitchik', 'Rav Yitzchak Zev Soloveitchik'],
  '13-27': ['Rav Chaim ibn Attar (Or HaChaim)', 'Rav Yonah of Gerondi'],
  '13-28': ['Rav Shmuel Eidels (Maharsha)', 'Rav Moshe Isserles'],
  '13-29': ['Rashi', 'Rav Yaakov ben Asher'],
};

/** Get the gedolim for a Hebrew date. Returns [rabbi1, rabbi2] or null. Uses year % 2 to pick which to show. */
export function getGedolimForDate(
  hebrewDay: number,
  hebrewMonth: number,
  hebrewYear: number
): string | null {
  const key = gedolimKey(hebrewMonth, hebrewDay);
  const entry = GEDOLIM_YAHRZEITS[key];
  if (!entry) return null;
  const index = hebrewYear % 2;
  return entry[index];
}

/** Get both rabbis for a Hebrew date (for display when desired). */
export function getBothGedolimForDate(
  hebrewDay: number,
  hebrewMonth: number
): GedolimEntry | null {
  const key = gedolimKey(hebrewMonth, hebrewDay);
  return GEDOLIM_YAHRZEITS[key] ?? null;
}
