/**
 * Static content for home screen learning widgets.
 * 100-day cycle: same content repeats every 100 days so users don't see duplicates for 100 days.
 */

const EPOCH_MS = new Date(2020, 0, 1).getTime();
const MS_PER_DAY = 86400000;

/** Returns 0..99 for a 100-day cycle (same index for 100 days, then repeats). */
export function getIndex100(): number {
  const daysSince = Math.floor((Date.now() - EPOCH_MS) / MS_PER_DAY);
  return Math.abs(daysSince % 100);
}

/** Get content for today from an array; uses 100-day cycle so no duplicate for 100 days. */
export function getByDay100<T>(arr: T[]): T {
  const i = getIndex100() % arr.length;
  return arr[i];
}

export const INSPIRATION_QUOTES: { text: string; translation: string; source: string }[] = [
  { text: "אִם אֵין אֲנִי לִי, מִי לִי", translation: "If I am not for myself, who will be for me?", source: "Hillel, Pirkei Avos" },
  { text: "בְּמָקוֹם שֶׁאֵין אֲנָשִׁים, הִשְׁתַּדֵּל לִהְיוֹת אִישׁ", translation: "In a place where there are no leaders, strive to be a leader.", source: "Pirkei Avos" },
  { text: "הֱוֵי מְקַבֵּל אֶת כָּל הָאָדָם בְּסֵבֶר פָּנִים יָפוֹת", translation: "Greet everyone with a cheerful face.", source: "Shammai, Pirkei Avos" },
  { text: "אַל תִּסְתַּכֵּל בַּקַּנְקַן, אֶלָּא בְּמַה שֶּׁיֵּשׁ בּוֹ", translation: "Do not look at the vessel, but at what it contains.", source: "Pirkei Avos" },
  { text: "וְאָהַבְתָּ לְרֵעֲךָ כָּמוֹךָ", translation: "Love your neighbor as yourself.", source: "Vayikra 19:18" },
  { text: "וּבָחַרְתָּ בַּחַיִּים", translation: "Choose life.", source: "Devarim 30:19" },
  { text: "צֶדֶק צֶדֶק תִּרְדֹּף", translation: "Justice, justice shall you pursue.", source: "Devarim 16:20" },
  { text: "שְׁמַע יִשְׂרָאֵל ה' אֱלֹהֵינוּ ה' אֶחָד", translation: "Hear O Israel: Hashem is our God, Hashem is One.", source: "Devarim 6:4" },
  { text: "וְעָשִׂיתָ הַיָּשָׁר וְהַטּוֹב", translation: "Do what is right and good.", source: "Devarim 6:18" },
  { text: "לֹא תִשָּׂא אֶת שֵׁם ה' לַשָּׁוְא", translation: "Do not take the name of Hashem in vain.", source: "Shemos 20:7" },
  { text: "כַּבֵּד אֶת אָבִיךָ וְאֶת אִמֶּךָ", translation: "Honor your father and mother.", source: "Shemos 20:12" },
  { text: "ה' אֱלֹהֶיךָ בְּקִרְבֶּךָ", translation: "Hashem your God is in your midst.", source: "Tzefania 3:17" },
  { text: "יִרְאַת ה' רֵאשִׁית דָּעַת", translation: "The fear of Hashem is the beginning of wisdom.", source: "Mishlei 1:7" },
  { text: "בְּטַח אֶל ה' בְּכָל לִבֶּךָ", translation: "Trust in Hashem with all your heart.", source: "Mishlei 3:5" },
  { text: "בְּכָל דְּרָכֶיךָ דָּעֵהוּ", translation: "In all your ways know Him.", source: "Mishlei 3:6" },
  { text: "חָכְמָה בַּחוּץ תָּרֹנָּה", translation: "Wisdom calls aloud in the street.", source: "Mishlei 1:20" },
  { text: "צְדָקָה תַּצִּיל מִמָּוֶת", translation: "Righteousness delivers from death.", source: "Mishlei 10:2" },
  { text: "אֹרַח חַיִּים לְמַעְלָה לְמַשְׂכִּיל", translation: "The path of life is upward for the wise.", source: "Mishlei 15:24" },
  { text: "לֵב שָׂמֵחַ יֵיטִיב גֵּהָה", translation: "A joyful heart makes for good healing.", source: "Mishlei 17:22" },
  { text: "חֶסֶד וֶאֱמֶת אַל יַעַזְבוּךָ", translation: "Let kindness and truth not forsake you.", source: "Mishlei 3:3" },
  { text: "ה' מָעוֹז חַיַּי מִמִּי אֶפְחָד", translation: "Hashem is the stronghold of my life; of whom shall I be afraid?", source: "Tehillim 27:1" },
  { text: "שִׁוִּיתִי ה' לְנֶגְדִּי תָמִיד", translation: "I have set Hashem before me always.", source: "Tehillim 16:8" },
  { text: "טוֹב לְהוֹדוֹת לַה'", translation: "It is good to give thanks to Hashem.", source: "Tehillim 92:2" },
  { text: "ה' רֹעִי לֹא אֶחְסָר", translation: "Hashem is my shepherd; I shall not want.", source: "Tehillim 23:1" },
  { text: "ה' אוֹרִי וְיִשְׁעִי", translation: "Hashem is my light and my salvation.", source: "Tehillim 27:1" },
  { text: "קָרוֹב ה' לְכָל קוֹרְאָיו", translation: "Hashem is close to all who call upon Him.", source: "Tehillim 145:18" },
  { text: "פּוֹתֵחַ אֶת יָדֶךָ וּמַשְׂבִּיעַ לְכָל חַי רָצוֹן", translation: "You open Your hand and satisfy every living thing.", source: "Tehillim 145:16" },
  { text: "כָּל נְשָׁמָה תְּהַלֵּל יָ-הּ", translation: "Let every soul praise God.", source: "Tehillim 150:6" },
  { text: "הַטֵּף אֵלַי חֶסֶד כִּי עָנִי אָנִי", translation: "Bestow Your kindness upon me, for I am poor.", source: "Tehillim 86:1" },
  { text: "לְדָוִד ה' אוֹרִי וְיִשְׁעִי", translation: "Of David: Hashem is my light and my salvation.", source: "Tehillim 27:1" },
  { text: "אַשְׁרֵי יוֹשְׁבֵי בֵיתֶךָ עוֹד יְהַלְלוּךָ סֶּלָה", translation: "Fortunate are those who dwell in Your house; they will praise You forever.", source: "Tehillim 84:5" },
  { text: "שִׁמְעוּ בָּנִים מוּסַר אָב", translation: "Listen, children, to the discipline of a father.", source: "Mishlei 4:1" },
  { text: "הַקְשֵׁב לְחָכְמָה אָזְנֶךָ", translation: "Incline your ear to wisdom.", source: "Mishlei 2:2" },
  { text: "כִּי נֵר מִצְוָה וְתוֹרָה אוֹר", translation: "For a mitzvah is a lamp and Torah is light.", source: "Mishlei 6:23" },
  { text: "דְּרָכֶיהָ דַּרְכֵי נֹעַם", translation: "Her ways are ways of pleasantness.", source: "Mishlei 3:17" },
  { text: "עֵץ חַיִּים הִיא לַמַּחֲזִיקִים בָּהּ", translation: "It is a tree of life to those who grasp it.", source: "Mishlei 3:18" },
  { text: "אַשְׁרֵי אָדָם שֹׁמֵעַ לִי", translation: "Fortunate is the person who listens to me.", source: "Mishlei 8:34" },
  { text: "יָגַעְתָּ בְּכָל מַעֲשֶׂיךָ", translation: "You have wearied yourself in all your works.", source: "Yeshayahu 43:22" },
  { text: "קוּמִי אוֹרִי כִּי בָא אוֹרֵךְ", translation: "Arise, shine, for your light has come.", source: "Yeshayahu 60:1" },
  { text: "נַחֲמוּ נַחֲמוּ עַמִּי", translation: "Comfort, comfort My people.", source: "Yeshayahu 40:1" },
  { text: "וְהַחֲזַקְתֶּם אֶת יְדֵי הַחַלָּשִׁים", translation: "Strengthen the hands of the weak.", source: "Yechezkel 34:4" },
  { text: "וְעָשִׂיתָ הָאֱמֶת וְהַחֶסֶד", translation: "Do truth and kindness.", source: "Bereishis 47:29" },
  { text: "ה' יִשְׁמָר צֵאתְךָ וּבוֹאֶךָ", translation: "Hashem will guard your going and coming.", source: "Tehillim 121:8" },
  { text: "אֵין כָּמוֹךָ בָאֱלֹהִים ה'", translation: "There is none like You among the gods, Hashem.", source: "Tehillim 86:8" },
  { text: "ה' צַדִּיק יִבְחָן", translation: "Hashem tests the righteous.", source: "Tehillim 11:5" },
  { text: "זְכֹר רַחֲמֶיךָ ה' וַחֲסָדֶיךָ", translation: "Remember Your mercies, Hashem, and Your kindnesses.", source: "Tehillim 25:6" },
  { text: "הוֹדוּ לַה' כִּי טוֹב", translation: "Give thanks to Hashem, for He is good.", source: "Tehillim 118:1" },
  { text: "זֶה הַיּוֹם עָשָׂה ה' נָגִילָה וְנִשְׂמְחָה בוֹ", translation: "This is the day Hashem has made; let us rejoice and be glad in it.", source: "Tehillim 118:24" },
  { text: "מִמַּעֲמַקִּים קְרָאתִיךָ ה'", translation: "From the depths I have called You, Hashem.", source: "Tehillim 130:1" },
  { text: "שִׁוִּיתִי ה' לְנֶגְדִּי תָמִיד כִּי מִימִינִי בַּל אֶמּוֹט", translation: "I have set Hashem before me always; He is at my right hand, I shall not falter.", source: "Tehillim 16:8" },
  { text: "הַטֵּף חַסְדְּךָ לְיוֹדְעֶיךָ", translation: "Bestow Your kindness upon those who know You.", source: "Tehillim 36:11" },
  { text: "כִּי עִמְּךָ מְקוֹר חַיִּים", translation: "For with You is the source of life.", source: "Tehillim 36:10" },
  { text: "גָּדוֹל ה' וּמְהֻלָּל מְאֹד", translation: "Great is Hashem and greatly to be praised.", source: "Tehillim 48:2" },
  { text: "וְאַתָּה קָדוֹשׁ יוֹשֵׁב תְּהִלּוֹת יִשְׂרָאֵל", translation: "And You are holy, enthroned upon the praises of Israel.", source: "Tehillim 22:4" },
  { text: "ה' עֹז לְעַמּוֹ יִתֵּן", translation: "Hashem will give strength to His people.", source: "Tehillim 29:11" },
  { text: "שְׁמַע ה' קוֹלִי אֶקְרָא", translation: "Hear, Hashem, my voice when I call.", source: "Tehillim 27:7" },
  { text: "אַחַת שָׁאַלְתִּי מֵאֵת ה'", translation: "One thing I have asked of Hashem.", source: "Tehillim 27:4" },
  { text: "לֶחֶם לֹא אֶכַל וְמַיִם לֹא אֶשְׁתֶּה", translation: "I will not eat bread nor drink water.", source: "Shemos 34:28" },
  { text: "וְהָיָה ה' לִמֶּנּוּ לֵאלֹהִים", translation: "And Hashem will be for us a God.", source: "Shemos 6:7" },
  { text: "אָנֹכִי ה' אֱלֹהֶיךָ", translation: "I am Hashem your God.", source: "Shemos 20:2" },
  { text: "וְזָכַרְתָּ אֶת ה' אֱלֹהֶיךָ", translation: "And you shall remember Hashem your God.", source: "Devarim 8:18" },
  { text: "ה' אֶחָד וּשְׁמוֹ אֶחָד", translation: "Hashem is One and His name is One.", source: "Zechariah 14:9" },
  { text: "לֹא יִגַּע לָרִיק", translation: "He will not labor in vain.", source: "Yeshayahu 65:23" },
  { text: "וְהָאָרֶץ תִּמָּלֵא דֵּעָה אֶת ה'", translation: "And the earth will be filled with knowledge of Hashem.", source: "Yeshayahu 11:9" },
  { text: "בַּה' בָּטַחְתִּי אַל אִירָא", translation: "In Hashem I trusted; I shall not fear.", source: "Tehillim 56:12" },
  { text: "חַסְדֵי ה' כִּי לֹא תָמְנוּ", translation: "The kindnesses of Hashem never cease.", source: "Eichah 3:22" },
  { text: "חֲדָשִׁים לַבְּקָרִים רַבָּה אֱמוּנָתֶךָ", translation: "They are new every morning; great is Your faithfulness.", source: "Eichah 3:23" },
  { text: "ה' חֵלְקִי אָמְרָה נַפְשִׁי", translation: "Hashem is my portion, says my soul.", source: "Eichah 3:24" },
  { text: "טוֹב וִישַׁר ה'", translation: "Hashem is good and upright.", source: "Tehillim 25:8" },
  { text: "יַדְּרֵךְ עֲנָוִים בַּמִּשְׁפָּט", translation: "He guides the humble in justice.", source: "Tehillim 25:9" },
  { text: "כָּל מַעְבְּרוֹת ה' אֱמֶת וֶאֱמוּנָה", translation: "All Hashem's paths are kindness and truth.", source: "Tehillim 25:10" },
  { text: "לְמִי יֵשׁ חֶסֶד ה'", translation: "Who has Hashem's kindness?", source: "Tehillim 4:4" },
  { text: "רַבִּים אֹמְרִים מִי יַרְאֵנוּ טוֹב", translation: "Many say: Who will show us good?", source: "Tehillim 4:7" },
  { text: "נָשָׂאתָ פָנֶיךָ ה'", translation: "You have lifted the light of Your face, Hashem.", source: "Tehillim 4:7" },
  { text: "בְּשִׁמְךָ נְרַנֵּנָה כָּל הַיּוֹם", translation: "In Your name we will rejoice all day.", source: "Tehillim 44:9" },
  { text: "אֱלֹהִים בְּאָזְנֵינוּ שָׁמַעְנוּ", translation: "We have heard with our ears, O God.", source: "Tehillim 44:2" },
  { text: "ה' מָלַךְ גֵּאוּת לָבֵשׁ", translation: "Hashem has reigned; He has donned majesty.", source: "Tehillim 93:1" },
  { text: "נַפְשִׁי אוֹמֶרֶת לַה' מָעוּזִּי וּמְנוּסִי", translation: "My soul says to Hashem: You are my stronghold and refuge.", source: "Tehillim 62:2" },
  { text: "אַךְ אֱלֹהִים יִדְּמֶן לָנוּ", translation: "Only for God wait in stillness, my soul.", source: "Tehillim 62:6" },
  { text: "כִּי מִמֶּנּוּ תּוֹצְאוֹת חַיִּים", translation: "For from Him are the issues of life.", source: "Mishlei 4:23" },
  { text: "שָׁמֹר בָּנִי מִצְוָתִי וֶחֱיֵה", translation: "Keep my commandment, my son, and live.", source: "Mishlei 7:2" },
  { text: "קְנֵה חָכְמָה קְנֵה בִּינָה", translation: "Acquire wisdom; acquire understanding.", source: "Mishlei 4:5" },
  { text: "אַל תַּעַזְבֶהָ וְתִשְׁמְרֶךָּ", translation: "Do not forsake her, and she will guard you.", source: "Mishlei 4:6" },
  { text: "רֵאשִׁית חָכְמָה קְנֵה חָכְמָה", translation: "The beginning of wisdom is: acquire wisdom.", source: "Mishlei 4:7" },
  { text: "כָּל דִּבְרֵי פִי בֶּאֱמוּנָה", translation: "All the words of my mouth are in faithfulness.", source: "Mishlei 8:8" },
  { text: "צֶדֶק וּמִשְׁפָּט מְכוֹן כִּסְאֶךָ", translation: "Righteousness and justice are the foundation of Your throne.", source: "Tehillim 89:15" },
  { text: "חֶסֶד וֶאֱמֶת יְקַדְּמוּ פָנֶיךָ", translation: "Kindness and truth go before You.", source: "Tehillim 89:15" },
  { text: "הוֹדוּ לַה' בְּכִנּוֹר", translation: "Give thanks to Hashem with the harp.", source: "Tehillim 33:2" },
  { text: "זַמְּרוּ לוֹ בְּנֵבֶל עָשׂוֹר", translation: "Sing to Him with a ten-stringed harp.", source: "Tehillim 33:2" },
  { text: "דִּרְשׁוּ ה' וְעֻזּוֹ", translation: "Seek Hashem and His strength.", source: "Tehillim 105:4" },
  { text: "בַּקְּשׁוּ פָנָיו תָּמִיד", translation: "Seek His face constantly.", source: "Tehillim 105:4" },
  { text: "הוֹדוּ לַה' כִּי טוֹב כִּי לְעוֹלָם חַסְדּוֹ", translation: "Give thanks to Hashem for He is good, for His kindness is everlasting.", source: "Tehillim 106:1" },
  { text: "הַלְלוּיָהּ הַלְלוּ אֶת שֵׁם ה'", translation: "Hallelujah! Praise the name of Hashem.", source: "Tehillim 113:1" },
  { text: "מִמִּזְרַח שֶׁמֶשׁ עַד מְבוֹאוֹ", translation: "From the rising of the sun to its setting.", source: "Tehillim 113:3" },
  { text: "מְהֻלָּל שֵׁם כְּבוֹדוֹ", translation: "Praised is the name of His glory.", source: "Tehillim 72:19" },
  { text: "אֲבָרְכָה אֶת ה' בְּכָל עֵת", translation: "I will bless Hashem at all times.", source: "Tehillim 34:2" },
  { text: "תָּמִיד תְּהַלָּתוֹ בְּפִי", translation: "His praise is always in my mouth.", source: "Tehillim 34:2" },
  { text: "בְּה' הִתְהַלָּל נַפְשִׁי", translation: "My soul shall glory in Hashem.", source: "Tehillim 34:3" },
  { text: "יִשְׂמְחוּ עֲנָוִים וְיַעַלְצוּ", translation: "Let the humble hear and rejoice.", source: "Tehillim 34:3" },
  { text: "גַּדְּלוּ לַה' אִתִּי", translation: "Exalt Hashem with me.", source: "Tehillim 34:4" },
  { text: "וְנַרְוִימָה שְׁמוֹ יַחְדָּו", translation: "And let us exalt His name together.", source: "Tehillim 34:4" },
  { text: "דָּרַשְׁתִּי אֶת ה' וְעָנָנִי", translation: "I sought Hashem and He answered me.", source: "Tehillim 34:5" },
  { text: "וּמִכָּל מְגוּרוֹתַי הִצִּילָנִי", translation: "And from all my terrors He delivered me.", source: "Tehillim 34:5" },
  { text: "הִבִּיטוּ אֵלָיו וְנָהָרוּ", translation: "Look to Him and be radiant.", source: "Tehillim 34:6" },
  { text: "וּפְנֵיהֶם אַל יֶחְפָּרוּ", translation: "And their faces shall not be ashamed.", source: "Tehillim 34:6" },
  { text: "זֶה עָנִי קָרָא וַה' שָׁמֵעַ", translation: "This poor one called and Hashem heard.", source: "Tehillim 34:7" },
  { text: "וּמִכָּל צָרוֹתָיו הוֹשִׁיעוֹ", translation: "And from all his troubles He saved him.", source: "Tehillim 34:7" },
  { text: "חוֹנֶה מַלְאַךְ ה' סָבִיב לִירֵאָיו", translation: "The angel of Hashem encamps around those who fear Him.", source: "Tehillim 34:8" },
  { text: "וַיְחַלְּצֵם", translation: "And delivers them.", source: "Tehillim 34:8" },
  { text: "טַעֲמוּ וּרְאוּ כִּי טוֹב ה'", translation: "Taste and see that Hashem is good.", source: "Tehillim 34:9" },
  { text: "אַשְׁרֵי הַגֶּבֶר יֶחֱסֶה בּוֹ", translation: "Fortunate is the man who takes refuge in Him.", source: "Tehillim 34:9" },
  { text: "יְרוּאוּ אֶת ה' קְדוֹשָׁיו", translation: "Fear Hashem, you His holy ones.", source: "Tehillim 34:10" },
  { text: "כִּי אֵין מַחְסוֹר לִירֵאָיו", translation: "For there is no want to those who fear Him.", source: "Tehillim 34:10" },
  { text: "כְּפִירִים רָשׁוּ וְרָעֵבוּ", translation: "Young lions have lacked and been hungry.", source: "Tehillim 34:11" },
  { text: "וְדֹרְשֵׁי ה' לֹא יַחְסְרוּ כָל טוֹב", translation: "But those who seek Hashem shall not lack any good.", source: "Tehillim 34:11" },
  { text: "לְכוּ בָנִים שִׁמְעוּ לִי", translation: "Come, children, listen to me.", source: "Tehillim 34:12" },
  { text: "יִרְאַת ה' אֲלַמְּדֶכֶם", translation: "I will teach you the fear of Hashem.", source: "Tehillim 34:12" },
  { text: "מִי הָאִישׁ הֶחָפֵץ חַיִּים", translation: "Who is the man who desires life?", source: "Tehillim 34:13" },
  { text: "אֹהֵב יָמִים לִרְאוֹת טוֹב", translation: "Who loves days to see good?", source: "Tehillim 34:13" },
  { text: "נְצֹר לְשׁוֹנְךָ מֵרָע", translation: "Guard your tongue from evil.", source: "Tehillim 34:14" },
  { text: "וְשִׂפְתוֹתֶיךָ מִדַּבֵּר מִרְמָה", translation: "And your lips from speaking deceit.", source: "Tehillim 34:14" },
];

export const HEBREW_WORDS: { word: string; meaning: string }[] = [
  { word: 'שָׁלוֹם', meaning: 'Peace' },
  { word: 'תּוֹדָה', meaning: 'Thanks' },
  { word: 'אֱמֶת', meaning: 'Truth' },
  { word: 'חֶסֶד', meaning: 'Kindness' },
  { word: 'אֲהָבָה', meaning: 'Love' },
  { word: 'בִּטָּחוֹן', meaning: 'Trust' },
  { word: 'שִׂמְחָה', meaning: 'Joy' },
  { word: 'צְדָקָה', meaning: 'Charity' },
  { word: 'תְּפִלָּה', meaning: 'Prayer' },
  { word: 'תּוֹרָה', meaning: 'Torah' },
  { word: 'חָכְמָה', meaning: 'Wisdom' },
  { word: 'בְּרָכָה', meaning: 'Blessing' },
  { word: 'רַחֲמִים', meaning: 'Mercy' },
  { word: 'יֹשֶׁר', meaning: 'Integrity' },
  { word: 'אֱמוּנָה', meaning: 'Faith' },
  { word: 'תְּשׁוּבָה', meaning: 'Repentance' },
  { word: 'עֲנָוָה', meaning: 'Humility' },
  { word: 'סַבְלָנוּת', meaning: 'Patience' },
  { word: 'הַכָּרַת טוֹבָה', meaning: 'Gratitude' },
  { word: 'נְקִיּוּת', meaning: 'Purity' },
  { word: 'כָּבוֹד', meaning: 'Honor' },
  { word: 'חֵן', meaning: 'Grace' },
  { word: 'גְּבוּרָה', meaning: 'Courage' },
  { word: 'תִּקְוָה', meaning: 'Hope' },
  { word: 'נֶחָמָה', meaning: 'Comfort' },
  { word: 'שֶׁקֶט', meaning: 'Quiet' },
  { word: 'רֵעוּת', meaning: 'Friendship' },
  { word: 'מִשְׁפָּט', meaning: 'Justice' },
  { word: 'חֵרוּת', meaning: 'Freedom' },
  { word: 'זִכָּרוֹן', meaning: 'Memory' },
  { word: 'חַיִּים', meaning: 'Life' },
  { word: 'אוֹר', meaning: 'Light' },
  { word: 'טוֹב', meaning: 'Good' },
  { word: 'יֹפִי', meaning: 'Beauty' },
  { word: 'חֶמְלָה', meaning: 'Compassion' },
  { word: 'אַהֲבַת חִנָּם', meaning: 'Love without cause' },
  { word: 'צְנִיעוּת', meaning: 'Modesty' },
  { word: 'יִרְאָה', meaning: 'Awe' },
  { word: 'קְדֻשָּׁה', meaning: 'Holiness' },
  { word: 'שָׁלוֹם בַּיִת', meaning: 'Peace at home' },
  { word: 'לֵב', meaning: 'Heart' },
  { word: 'נֶפֶשׁ', meaning: 'Soul' },
  { word: 'רוּחַ', meaning: 'Spirit' },
  { word: 'מַחְשָׁבָה', meaning: 'Thought' },
  { word: 'דִּבּוּר', meaning: 'Speech' },
  { word: 'מַעֲשֶׂה', meaning: 'Action' },
  { word: 'מִצְוָה', meaning: 'Commandment' },
  { word: 'מִדָּה', meaning: 'Character trait' },
  { word: 'חֻקָּה', meaning: 'Statute' },
  { word: 'מִשְׁפָּט', meaning: 'Law' },
  { word: 'אַחֲרָיוּת', meaning: 'Responsibility' },
  { word: 'זְכוּת', meaning: 'Merit' },
  { word: 'חוֹבָה', meaning: 'Obligation' },
  { word: 'רְצוֹן', meaning: 'Will' },
  { word: 'כַּוָּנָה', meaning: 'Intention' },
  { word: 'הִתְבּוֹדְדוּת', meaning: 'Seclusion' },
  { word: 'הִתְפַּלְּלוּת', meaning: 'Prayer' },
  { word: 'לִמּוּד', meaning: 'Study' },
  { word: 'עֲבוֹדָה', meaning: 'Service' },
  { word: 'גְּמִילוּת חֲסָדִים', meaning: 'Acts of kindness' },
  { word: 'בִּקּוּר חוֹלִים', meaning: 'Visiting the sick' },
  { word: 'הַכְנָסַת אוֹרְחִים', meaning: 'Hospitality' },
  { word: 'נַחַת', meaning: 'Pleasure' },
  { word: 'שִׂמְחַת חִנָּם', meaning: 'Joy without cause' },
  { word: 'הוֹדָאָה', meaning: 'Thanksgiving' },
  { word: 'הַלֵּל', meaning: 'Praise' },
  { word: 'שִׁיר', meaning: 'Song' },
  { word: 'תְּהִלִּים', meaning: 'Psalms' },
  { word: 'בְּרֵאשִׁית', meaning: 'In the beginning' },
  { word: 'נֵר', meaning: 'Candle' },
  { word: 'שַׁבָּת', meaning: 'Sabbath' },
  { word: 'חַג', meaning: 'Holiday' },
  { word: 'רֹאשׁ חֹדֶשׁ', meaning: 'New month' },
  { word: 'תְּקוּפָה', meaning: 'Season' },
  { word: 'שָׁנָה', meaning: 'Year' },
  { word: 'יוֹם', meaning: 'Day' },
  { word: 'לַיְלָה', meaning: 'Night' },
  { word: 'בֹּקֶר', meaning: 'Morning' },
  { word: 'עֶרֶב', meaning: 'Evening' },
  { word: 'מָזוֹן', meaning: 'Sustenance' },
  { word: 'לֶחֶם', meaning: 'Bread' },
  { word: 'מַיִם', meaning: 'Water' },
  { word: 'נְשָׁמָה', meaning: 'Breath' },
  { word: 'חָזוֹן', meaning: 'Vision' },
  { word: 'נְבוּאָה', meaning: 'Prophecy' },
  { word: 'מַלְאָךְ', meaning: 'Angel' },
  { word: 'מָשִׁיחַ', meaning: 'Anointed' },
  { word: 'גְּאוּלָּה', meaning: 'Redemption' },
  { word: 'תְּקוּמָה', meaning: 'Resurrection' },
  { word: 'עוֹלָם', meaning: 'World' },
  { word: 'עַד', meaning: 'Eternity' },
  { word: 'שָׁמַיִם', meaning: 'Heaven' },
  { word: 'אֶרֶץ', meaning: 'Earth' },
  { word: 'אָדָם', meaning: 'Person' },
  { word: 'יִשְׂרָאֵל', meaning: 'Israel' },
  { word: 'בְּרִית', meaning: 'Covenant' },
  { word: 'זֶרַע', meaning: 'Seed' },
  { word: 'מוֹרָשָׁה', meaning: 'Heritage' },
  { word: 'מְנֻחָה', meaning: 'Rest' },
  { word: 'שָׁלָב', meaning: 'Stage' },
  { word: 'דֶּרֶךְ', meaning: 'Way' },
  { word: 'פֶּתַח', meaning: 'Opening' },
  { word: 'שַׁעַר', meaning: 'Gate' },
  { word: 'בַּיִת', meaning: 'House' },
  { word: 'מִקְדָּשׁ', meaning: 'Sanctuary' },
  { word: 'מִזְבֵּחַ', meaning: 'Altar' },
  { word: 'קָרְבָּן', meaning: 'Offering' },
  { word: 'תְּפִלִּין', meaning: 'Tefillin' },
  { word: 'מְזוּזָה', meaning: 'Mezuzah' },
  { word: 'צִיצִית', meaning: 'Tzitzit' },
  { word: 'כִּפָּה', meaning: 'Kippah' },
];

export const MUSSAR_QUOTES: string[] = [
  'Work on yourself first.',
  'Guard your tongue.',
  'Judge every person favorably.',
  'Be humble in your walk with Hashem.',
  'Trust in Hashem with all your heart.',
  'Return in peace—fix one thing today.',
  'Silence is a fence for wisdom.',
  'Who is wise? One who learns from every person.',
  'Who is strong? One who conquers his inclination.',
  'Who is rich? One who is satisfied with his portion.',
  'Say little and do much.',
  'The world stands on three things: Torah, avodah, and gemilus chasadim.',
  'Do not separate yourself from the community.',
  'Love peace and pursue it.',
  'Greet every person with a cheerful face.',
  'Do not judge your fellow until you are in his place.',
  'In a place where there are no leaders, strive to be a leader.',
  'That which is hateful to you, do not do to your fellow.',
  'What is mine is yours, and what is yours is yours—that is a chassid.',
  'Let your friend\'s honor be as dear to you as your own.',
  'Do not be easily angered.',
  'Repent one day before your death.',
  'Know what is above you: an eye that sees, an ear that hears.',
  'All is foreseen, yet free will is given.',
  'The day is short and the work is great.',
  'It is not upon you to finish the work, nor may you desist from it.',
  'Whoever destroys one soul is as if he destroyed an entire world.',
  'Whoever saves one soul is as if he saved an entire world.',
  'The Holy One desires the heart.',
  'Words that come from the heart enter the heart.',
  'A person is led on the path he wishes to follow.',
  'Envy, desire, and honor remove a person from the world.',
  'Whoever runs after honor, honor flees from him.',
  'Whoever flees from honor, honor runs after him.',
  'Open your hand to the poor.',
  'The reward of a mitzvah is a mitzvah.',
  'There is no person who does not have his hour.',
  'Do not believe in yourself until the day of your death.',
  'Remove your foot from your friend\'s house lest he have his fill of you.',
  'Woe to the wicked, woe to his neighbor.',
  'Do not appease your friend at the time of his anger.',
  'Distance yourself from a bad neighbor.',
  'Do not rely on your own understanding.',
  'In the place where there are no people, strive to be a person.',
  'Do not say "I will study when I have time"—lest you never have time.',
  'An ignorant person cannot be pious.',
  'A shy person cannot learn.',
  'An impatient person cannot teach.',
  'Where there is no flour, there is no Torah.',
  'If I am not for myself, who will be for me?',
  'When I am only for myself, what am I?',
  'If not now, when?',
  'The day is short, the work is great, the workers are lazy, the reward is great.',
  'Do not look at the vessel but at what it contains.',
  'Whoever increases flesh, increases worms.',
  'Whoever increases possessions, increases worry.',
  'Whoever increases servants, increases theft.',
  'Whoever increases Torah, increases life.',
  'A good heart is a continual feast.',
  'Better a good neighbor than a distant brother.',
  'A good name is better than good oil.',
  'The righteous one falls seven times and rises.',
  'Rejoice not when your enemy falls.',
  'Do not say "I will pay back evil"—wait for Hashem.',
  'A soft answer turns away wrath.',
  'Pride goes before destruction.',
  'Train a child in the way he should go.',
  'The fear of Hashem is the beginning of wisdom.',
  'Trust in Hashem with all your heart; do not lean on your own understanding.',
  'In all your ways know Him, and He will straighten your paths.',
  'Do not be wise in your own eyes; fear Hashem.',
  'Honor Hashem with your wealth.',
  'The soul of man is the lamp of Hashem.',
  'A mitzvah is a lamp and Torah is light.',
  'The path of the righteous is like the light of dawn.',
  'Righteousness exalts a nation.',
  'The memory of the righteous is a blessing.',
  'The wise of heart will receive commandments.',
  'A man\'s heart devises his way, but Hashem directs his steps.',
  'Commit your works to Hashem and your plans will be established.',
  'The beginning of wisdom is: acquire wisdom.',
  'Hear, my child, the instruction of your father.',
  'Bind them on your heart; tie them on your neck.',
  'When you walk they will lead you.',
  'For they are life to those who find them.',
  'Guard your heart, for from it come the issues of life.',
  'Put away from you crooked speech.',
  'Let your eyes look straight ahead.',
  'Do not be among those who drink wine.',
  'Who has woe? Those who linger at the wine.',
  'Look not upon the wine when it is red.',
  'Buy truth and do not sell it.',
  'A worthy woman, who can find?',
  'She opens her hand to the poor.',
  'Strength and dignity are her clothing.',
  'She opens her mouth with wisdom.',
  'Her children rise and call her blessed.',
  'Many have done worthily, but you surpass them all.',
  'Charm is deceitful and beauty is vain; a woman who fears Hashem, she shall be praised.',
  'The words of the wise are like goads.',
  'Fear Hashem and keep His commandments, for this is the whole person.',
  'The end of the matter, all having been heard: fear Hashem.',
  'Remember your Creator in the days of your youth.',
  'A time for every matter under heaven.',
  'He has made everything beautiful in its time.',
  'Two are better than one.',
  'Cast your bread upon the waters.',
  'In the morning sow your seed.',
  'The living know they will die.',
  'Let your garments always be white.',
  'Wisdom is good with an inheritance.',
  'A good name is better than precious oil.',
  'The heart of the wise is in the house of mourning.',
  'It is better to go to the house of mourning than to the house of feasting.',
  'Sorrow is better than laughter.',
  'The end of a matter is better than its beginning.',
  'Do not be quick to anger.',
  'Do not say "Why were the former days better?"',
  'Wisdom gives strength to the wise.',
  'One who digs a pit may fall into it.',
  'Words of the wise spoken quietly are heard.',
  'A living dog is better than a dead lion.',
  'For to the one who is joined to all the living there is hope.',
  'Whatever your hand finds to do, do with your might.',
  'The race is not to the swift nor the battle to the strong.',
  'He has set eternity in the heart of man.',
  'Two are better than one; they have a good reward for their toil.',
  'A threefold cord is not quickly broken.',
  'Better is a poor and wise youth than an old and foolish king.',
  'Guard your step when you go to the house of Hashem.',
  'Be not rash with your mouth.',
  'Let your words be few.',
  'When you make a vow to Hashem, do not delay to pay it.',
  'Fear Hashem and keep His commandments.',
  'For Hashem will bring every deed into judgment.',
];

export const RAMBAM_DAILY_LINES: string[] = [
  'Hilchos Yesodei HaTorah: foundations of faith.',
  'Hilchos Deios: character and emotional balance.',
  'Hilchos Talmud Torah: the mitzvah of study.',
  'Hilchos Tefillin: the mitzvah of tefillin.',
  'Hilchos Brachos: blessings and gratitude.',
  'Hilchos Teshuvah: repentance and return.',
  'Hilchos Melachim: the days of Mashiach.',
  'Hilchos Avodas Kochavim: not to turn to idolatry.',
  'Hilchos Geirushin: the laws of divorce.',
  'Hilchos Ishus: marriage and the ketubah.',
  'Hilchos Nedarim: vows and their annulment.',
  'Hilchos Shevuos: oaths.',
  'Hilchos Shecheinim: neighbors and damages.',
  'Hilchos Sanhedrin: courts and testimony.',
  'Hilchos Edus: witnesses.',
  'Hilchos Mamrim: rebels and the authority of the court.',
  'Hilchos Aveil: mourning.',
  'Hilchos Sefer Torah: the Torah scroll.',
  'Hilchos Beis HaBechira: the Temple.',
  'Hilchos Klei HaMikdash: the vessels of the Temple.',
  'Hilchos Bi\'as HaMikdash: entering the Temple.',
  'Hilchos Ma\'aseh HaKorbanos: the sacrificial service.',
  'Hilchos Temidin: the daily and mussaf offerings.',
  'Hilchos Pesulei HaMukdashin: that which is disqualified.',
  'Hilchos Shechtah: ritual slaughter.',
  'Hilchos Kiddush HaChodesh: sanctifying the new month.',
  'Hilchos Shabbos: the Sabbath.',
  'Hilchos Eruvin: the Sabbath boundaries.',
  'Hilchos Yom Tov: the festivals.',
  'Hilchos Chametz U\'Matzah: chametz and matzah.',
  'Hilchos Shofar: the shofar.',
  'Hilchos Lulav: the four species.',
  'Hilchos Shekalim: the half-shekel.',
  'Hilchos Kiddush HaChodesh: the new moon.',
  'Hilchos Taaniyos: fasts.',
  'Hilchos Megillah: Purim and the megillah.',
  'Hilchos Chanukah: the eight days of Chanukah.',
  'Hilchos Ishut: betrothal and marriage.',
  'Hilchos Gerushin: divorce documents.',
  'Hilchos Yibum: levirate marriage.',
  'Hilchos Naarah Betulah: the virgin maiden.',
  'Hilchos Sotah: the wayward wife.',
  'Hilchos Avadim: servants.',
  'Hilchos Gezeilah: theft.',
  'Hilchos Geneivah: stealth and robbery.',
  'Hilchos Chovel: one who injures.',
  'Hilchos Rotzeach: murder and preserving life.',
  'Hilchos Nizkei Mamon: damage to property.',
  'Hilchos To\'en VeNit\'an: plaintiff and defendant.',
  'Hilchos Malveh VeLoveh: lender and borrower.',
  'Hilchos Sh\'eilah: borrowing and deposit.',
  'Hilchos Mechirah: sales.',
  'Hilchos Zechiyah: acquisition.',
  'Hilchos Shechenim: neighbors.',
  'Hilchos Shluchin: agents.',
  'Hilchos Avadim: slaves.',
  'Hilchos Geirushin: divorce.',
  'Hilchos Ishut: marriage.',
  'Yesodei HaTorah: the existence of G-d and His unity.',
  'Deios: the middle path and character traits.',
  'Talmud Torah: the obligation to study and teach.',
  'Avodah Zarah: idolatry and related prohibitions.',
  'Teshuvah: repentance.',
  'Kriyas Shema: the Shema and its brachos.',
  'Tefillah: prayer and the Amidah.',
  'Birkas Kohanim: the priestly blessing.',
  'Tefillin: tefillin.',
  'Mezuzah: the mezuzah.',
  'Sefer Torah: the Torah scroll.',
  'Tzitzis: tzitzis.',
  'Brachos: blessings over food and mitzvos.',
  'Milah: circumcision.',
  'Seder Tefillos: the order of daily prayers.',
  'Shabbos: the Sabbath and its prohibitions.',
  'Eruvin: combining domains for Shabbos.',
  'Yom Tov: the festivals and rest.',
  'Chametz U\'Matzah: Pesach.',
  'Shofar: Rosh Hashanah.',
  'Sukkah: the sukkah.',
  'Lulav: the four species.',
  'Shekalim: the half-shekel for the Temple.',
  'Kiddush HaChodesh: sanctifying the new month.',
  'Taaniyos: fast days.',
  'Megillah V\'Chanukah: Purim and Chanukah.',
  'Ishut: marriage.',
  'Gerushin: divorce.',
  'Yibum VaChalitzah: levirate marriage.',
  'Naarah Betulah: the seduced maiden.',
  'Sotah: the wayward wife.',
  'N\'arim: the wayward son.',
  'Avadim: Hebrew servants.',
  'Gezeilah VaAveidah: theft and lost property.',
  'Chovel UMazik: injury and damage.',
  'Rotzeach UShemiras Nefesh: murder and saving life.',
  'Nizkei Mamon: damage by one\'s property.',
  'Geneivah: theft.',
  'Gezeilah: robbery.',
  'Chovel: wounding.',
  'To\'en VeNit\'an: claims and counterclaims.',
  'Malveh VeLoveh: lending and borrowing.',
  'Sh\'eilah U\'Pikadon: deposit and borrowing.',
  'Mechirah: sales.',
  'Zechiyah U\'Matanah: acquisition and gift.',
  'Shechenim: neighbors.',
  'Shluchin VeShutafin: agents and partners.',
  'Avadim: slaves.',
  'Sechirus: hiring.',
  'She\'eilah U\'Pikadon: borrowing and deposit.',
  'Malveh VeLoveh: lender and borrower.',
  'To\'en VeNit\'an: plaintiff and defendant.',
  'Nachalos: inheritance.',
  'Sanhedrin: courts.',
  'Edus: testimony.',
  'Mamrim: rebels.',
  'Aveil: mourning.',
  'Melachim: kings and war.',
  'The Rambam: "Know that the Torah has two parts: the body of the Torah and its soul."',
  'The Rambam: "The purpose of the mitzvos is to bring the person to perfection."',
  'The Rambam: "The highest level of wisdom is to know G-d."',
  'The Rambam: "Teshuvah brings close those who were far."',
  'The Rambam: "The world was created for Torah and for those who keep it."',
  'The Rambam: "A person should always see himself as half guilty and half meritorious."',
  'The Rambam: "The entire Torah is for the sake of peace."',
  'The Rambam: "Great is tzedakah, for it brings the redemption closer."',
  'The Rambam: "Whoever is merciful to others receives mercy from Heaven."',
  'The Rambam: "The wise person does not speak before one greater than he in wisdom."',
];

export const HALACHA_ONE_LINERS: string[] = [
  'Wash hands when waking; say the bracha Al Netilas Yadayim.',
  'Say Birchas HaTorah before learning Torah each day.',
  'Minimize talking during the meal; bentch with kavanah.',
  'Give tzedakah daily, even a small amount.',
  'Visit the sick; saying Tehillim for them helps.',
  'Honor parents in word and deed every day.',
  'Guard your speech; avoid lashon hara.',
  'Recite Modeh Ani upon waking, before washing.',
  'Put on tzitzis (and tallis for Shacharis) each morning.',
  'Men: lay tefillin on weekdays (not Shabbos or Yom Tov).',
  'Check tzitzis for tears; all four strings and knots must be intact.',
  'Say Asher Yatzar after using the bathroom.',
  'Recite brachos before and after eating; wash for bread.',
  'Do not speak between washing for bread and the first bite.',
  'Bentch (Birkas HaMazon) after eating a kezayis of bread.',
  'Say Shema in the morning and evening within its zmanim.',
  'Daven Shacharis, Mincha, and Maariv (or at least Mincha and Maariv).',
  'Light Shabbos candles before sunset on Friday.',
  'Make Kiddush on Friday night and Shabbos day.',
  'Do not do melachah on Shabbos; keep it holy.',
  'Make Havdalah after Shabbos when three stars are out.',
  'On Yom Tov, light candles and keep the day as holy.',
  'On Pesach, do not own or eat chametz.',
  'Count the Omer each night from the second night of Pesach.',
  'Hear the shofar on Rosh Hashanah.',
  'Fast and repent on Yom Kippur.',
  'Dwell in the sukkah and take the four species on Sukkos.',
  'Light the menorah on each night of Chanukah.',
  'Hear the Megillah on Purim and give mishloach manos.',
  'Say Al HaNissim on Chanukah and Purim in the Amidah and bentching.',
  'On Rosh Chodesh, say Yaaleh V\'Yavo in the Amidah and bentching.',
  'When raining in winter (diaspora), say V\'Ten Tal U\'Matar in the Amidah.',
  'From Pesach to Shemini Atzeres, say Morid HaTal (Sefard) or omit Mashiv HaRuach.',
  'Do not eat or drink before Shacharis (except water in some opinions).',
  'Stand for Kaddish, Kedushah, and Barchu.',
  'Answer Amen to brachos; answer the key phrases in Kaddish.',
  'Do not interrupt between Baruch She\'Amar and Yishtabach in Pesukei D\'Zimra.',
  'Do not speak from the start of the Amidah until after Oseh Shalom.',
  'Take three steps back and forward before and after the Amidah.',
  'On a fast day (except Yom Kippur), say Aneinu in Mincha.',
  'On Tisha B\'Av, say Nachem in Mincha.',
  'Skip Tachanun on Shabbos, Yom Tov, Rosh Chodesh, and other days.',
  'Say full or half Hallel on the appropriate days.',
  'Wash netilas yadayim before eating bread (and after if needed).',
  'Do not eat meat and milk together; wait after meat before dairy.',
  'Check vegetables and grains for insects before eating.',
  'Say the bracha after using the bathroom (Asher Yatzar).',
  'Recite brachos on fragrances, lightning, and other phenomena when applicable.',
  'Honor the dead: attend the funeral and comfort mourners.',
  'Visit the sick; one-sixtieth of the illness is removed.',
  'Give at least ten percent of profit to tzedakah (maaser).',
  'Do not embarrass another person in public.',
  'Do not take revenge or bear a grudge.',
  'Rebuke your fellow when he does wrong, but in private and with love.',
  'Love your fellow as yourself; this is a great principle of the Torah.',
  'Judge every person favorably.',
  'Do not stand idly by your neighbor\'s blood.',
  'Return a lost object to its owner.',
  'Do not place a stumbling block before the blind.',
  'Rise before the elderly and honor the Torah scholar.',
  'Do not curse a Jew, and certainly not a parent.',
  'Honor your father and mother.',
  'Do not steal, rob, or swear falsely.',
  'Keep your word; do not break a vow.',
  'Do not delay paying a worker his wages.',
  'Leave peah and leket for the poor (in Israel).',
  'Do not muzzle an ox while it threshes.',
  'Send away the mother bird before taking the young.',
  'Build a maakeh (railing) on your roof.',
  'Do not mix kilayim (certain species) in planting or in garments.',
  'Do not shave the corners of the beard (for men).',
  'Marry and have children; honor your spouse.',
  'Learn Torah and teach it; fix times for Torah.',
  'Write a Sefer Torah (or participate in writing one).',
  'Recite the Shema twice daily.',
  'Tefillin on the arm and head (men, weekdays).',
  'Tzitzis on a four-cornered garment.',
  'Mezuzah on the doorposts of your home.',
  'Kiddush on Shabbos; Havdalah after Shabbos.',
  'Rest on Shabbos; do not do the 39 melachos.',
  'Celebrate the festivals; rest and rejoice on them.',
  'On Pesach: tell the story, eat matzah, avoid chametz.',
  'Count the Omer 49 days.',
  'Hear the shofar on Rosh Hashanah.',
  'Fast on Yom Kippur; repent and confess.',
  'Dwell in the sukkah; take the four species.',
  'Rejoice on the festivals; bring korbanos (when there is a Beis HaMikdash).',
  'Assemble the nation to hear the Torah every seven years (Hakhel).',
  'Give half a shekel annually (when there is a Beis HaMikdash).',
  'Honor the kohen; give him the terumos and maasros (in Israel).',
  'Do not eat or drink on Yom Kippur.',
  'Fast on the four fasts (Tzom Gedaliah, Asara B\'Teves, Shiva Asar B\'Tammuz, Tisha B\'Av).',
  'Cry out to Hashem in prayer in times of trouble.',
  'Convert the ger (convert) and love him.',
  'Do not oppress or wrong the ger.',
  'Weights and measures must be honest.',
  'Do not curse a nasi or a judge.',
  'Do not curse a parent, even after death.',
  'A kohen may not become tamei to a meis except for close relatives.',
  'The kohen gadol and nazir may not become tamei to any meis.',
  'A king must write a Sefer Torah; read it and keep it with him.',
  'Everyone must write or acquire a Sefer Torah.',
  'Bikkurim (first fruits) are brought to the Beis HaMikdash with joy.',
  'Confess one\'s sins and bring a korban when required.',
  'A woman after childbirth brings a korban.',
  'A metzora follows the laws of purity and brings korbanos.',
  'Give the tithes and terumos to the proper recipients.',
  'Leave the land fallow in the seventh year (shemittah) in Israel.',
  'Release loans in the shemittah year.',
  'Sound the shofar in the Yovel (jubilee) year.',
  'Sanctify the firstborn male kosher animal.',
  'Redeem the firstborn son (pidyon haben).',
  'Study and teach Torah; know it and do it.',
  'Say grace after meals when required.',
  'Affix a mezuzah; check it twice in seven years.',
  'Gather the people to hear the Torah on Sukkos of the eighth year.',
  'A king must not have too many horses, wives, or silver and gold.',
  'Every Jew must feel as if he left Egypt.',
  'Love Hashem with all your heart, soul, and might.',
  'Fear Hashem; serve Him and cling to Him.',
  'Swear only by His name when necessary.',
  'Imitate His ways: be merciful and gracious.',
  'Cleave to Torah scholars and their students.',
  'Do not follow the desires of the heart or the eyes.',
  'Do not test Hashem.',
  'Destroy idolatry and its accessories.',
  'Do not add or subtract from the mitzvos.',
  'Listen to the navi (prophet) in each generation.',
  'Do not fear the enemy in battle when Hashem is with you.',
  'Anoint a king from among your brethren when you enter the land.',
  'Build the Beis HaMikdash and do not delay.',
  'Revere the Mikdash; do not destroy its sanctity.',
];

export const TORAH_THOUGHTS: string[] = [
  'Every day we can choose to add a little more light.',
  'The Torah is called "a tree of life"—hold on to it.',
  'Small, steady steps build a life of meaning.',
  'Hashem is close to all who call to Him in truth.',
  'What is hateful to you, do not do to your neighbor.',
  'The world stands on Torah, avodah, and gemilus chasadim.',
  'Shabbos is a taste of the world to come.',
  'In the beginning G-d created the heaven and the earth.',
  'Let there be light—and there was light.',
  'And G-d saw everything that He had made, and behold it was very good.',
  'And G-d blessed the seventh day and sanctified it.',
  'Noach found favor in the eyes of Hashem.',
  'Go forth from your land, your birthplace, and your father\'s house.',
  'I will make you a great nation and bless you.',
  'And through you all the families of the earth shall be blessed.',
  'And he believed in Hashem, and He counted it to him as righteousness.',
  'Shall the Judge of all the earth not do justice?',
  'And you shall be a blessing.',
  'For I have known him, that he will command his children to keep the way of Hashem.',
  'And Hashem said: Shall I hide from Avraham what I am doing?',
  'And Avraham arose early in the morning and saddled his donkey.',
  'And he said: Here I am.',
  'G-d will see to the lamb for the offering.',
  'And they said: Naaseh v\'nishma—we will do and we will hear.',
  'And you shall love Hashem your G-d with all your heart.',
  'And you shall teach them diligently to your children.',
  'And you shall write them on the doorposts of your house.',
  'For this commandment is not in heaven—it is very close to you.',
  'Choose life, that you and your offspring may live.',
  'Justice, justice shall you pursue.',
  'You shall be holy, for I Hashem your G-d am holy.',
  'You shall love your fellow as yourself.',
  'Remember the Sabbath day to keep it holy.',
  'Honor your father and your mother.',
  'You shall not bear false witness.',
  'You shall not covet.',
  'The secret things belong to Hashem our G-d.',
  'The revealed things are for us and our children forever.',
  'For the mitzvah is a lamp and the Torah is light.',
  'Trust in Hashem with all your heart.',
  'In all your ways know Him, and He will straighten your paths.',
  'The fear of Hashem is the beginning of wisdom.',
  'A righteous person falls seven times and rises.',
  'As water reflects the face, so the heart of man reflects man.',
  'Train a child in the way he should go.',
  'A soft answer turns away wrath.',
  'Pride goes before destruction.',
  'Who is wise? One who learns from every person.',
  'Who is strong? One who conquers his inclination.',
  'Who is rich? One who is satisfied with his portion.',
  'Do not say I will study when I have time—lest you never have time.',
  'The day is short and the work is great.',
  'It is not upon you to finish the work, nor may you desist from it.',
  'Where there are no people, strive to be a person.',
  'That which is hateful to you, do not do to your fellow.',
  'What is mine is yours and what is yours is yours—that is a chassid.',
  'Let your friend\'s honor be as dear to you as your own.',
  'Repent one day before your death.',
  'All is foreseen, yet free will is given.',
  'The reward of a mitzvah is a mitzvah.',
  'Words that come from the heart enter the heart.',
  'A person is led on the path he wishes to follow.',
  'The Holy One desires the heart.',
  'Great is Torah for it gives life to those who do it.',
  'Turn it and turn it, for everything is in it.',
  'And you shall know today and set upon your heart that Hashem is G-d.',
  'There is none besides Him.',
  'And you shall serve Hashem your G-d with all your heart.',
  'And I will give the rain of your land in its season.',
  'And you shall eat and be satisfied.',
  'Take heed lest your heart be deceived and you turn aside.',
  'For the land which you are entering is not like the land of Egypt.',
  'A land that Hashem your G-d cares for; the eyes of Hashem are always upon it.',
  'Man does not live by bread alone, but by every word from the mouth of Hashem.',
  'You shall remember the entire way that Hashem your G-d led you.',
  'And He afflicted you and let you hunger and fed you the manna.',
  'So that He might make you know that man does not live by bread alone.',
  'And you shall bless Hashem your G-d for the good land He has given you.',
  'Beware lest you forget Hashem your G-d.',
  'And you say in your heart: My power and the might of my hand have gotten me this wealth.',
  'But you shall remember Hashem your G-d, for it is He who gives you power to get wealth.',
  'And now, Israel, what does Hashem your G-d require of you?',
  'Only to fear Hashem your G-d, to walk in all His ways, and to love Him.',
  'And to serve Hashem your G-d with all your heart and soul.',
  'To keep the commandments of Hashem and His statutes for your good.',
  'Behold, to Hashem your G-d belong heaven and the heaven of heavens.',
  'The earth with all that is in it.',
  'Yet Hashem set His love upon your fathers and chose their offspring after them.',
  'You above all peoples, as it is this day.',
  'Therefore circumcise the foreskin of your heart.',
  'And be no longer stiffnecked.',
  'For Hashem your G-d is the G-d of gods and the Lord of lords.',
  'He executes justice for the fatherless and the widow.',
  'He loves the ger, giving him food and clothing.',
  'Love the ger therefore, for you were gerim in the land of Egypt.',
  'You shall fear Hashem your G-d; Him you shall serve.',
  'And to Him you shall hold fast, and by His name you shall swear.',
  'He is your praise and He is your G-d.',
  'Who has done for you these great and awesome things.',
  'Your fathers went down to Egypt seventy persons.',
  'And now Hashem your G-d has made you as the stars of heaven for multitude.',
  'Therefore you shall love Hashem your G-d and keep His charge.',
  'And His statutes and His rules and His commandments always.',
  'And consider this day that Hashem is G-d in heaven above and on the earth beneath.',
  'There is no other.',
  'Therefore you shall keep His statutes and His commandments.',
  'Which I command you today, that it may go well with you and with your children.',
  'And that you may prolong your days in the land that Hashem your G-d is giving you forever.',
  'For the matter is very near to you, in your mouth and in your heart, to do it.',
  'See, I have set before you today life and good, death and evil.',
  'I call heaven and earth to witness against you today.',
  'That I have set before you life and death, blessing and curse.',
  'Therefore choose life, that you and your offspring may live.',
  'Loving Hashem your G-d, obeying His voice, and holding fast to Him.',
  'For He is your life and length of days.',
  'That you may dwell in the land that Hashem swore to your fathers.',
  'To Avraham, to Yitzchak, and to Yaakov, to give them.',
  'The Torah which Moshe commanded is the heritage of the congregation of Yaakov.',
  'And this is the blessing with which Moshe the man of G-d blessed the children of Israel.',
  'Happy are you, Israel! Who is like you, a people saved by Hashem.',
  'The eternal G-d is a dwelling place, and underneath are the everlasting arms.',
  'And He drove out the enemy from before you and said: Destroy!',
  'So Israel dwells in safety, the fountain of Yaakov alone.',
  'In a land of grain and wine; His heavens also drop down dew.',
  'Happy are you, Israel! Who is like you?',
  'A people saved by Hashem, the shield of your help.',
  'And the sword of your triumph; and your enemies shall submit to you.',
  'And you shall tread upon their high places.',
];

export const GEDOLIM_STORIES: string[] = [
  'The Chofetz Chaim was once asked how he achieved such greatness. He said: "I never spoke lashon hara."',
  'Rav Yisrael Salanter would delay minyan to help a stranger find his way—chessed before tefillah.',
  'The Vilna Gaon learned Torah day and night; he said sleep was a necessary evil.',
  'Rebbe Akiva started learning at 40; he said: "Whatever Hashem does is for the good."',
  'The Baal Shem Tov taught: in everything there is a lesson in serving Hashem.',
  'Hillel said: "That which is hateful to you, do not do to your fellow."',
  'Rashi explained the Torah so that a child could understand—clarity is kindness.',
  'When the Alter Rebbe was in prison, he was asked: "Why did G-d create the world?" He said: "So that the Jew could do teshuvah."',
  'The Steipler Gaon would not accept a gift without giving something in return—so the giver would not be embarrassed.',
  'Rav Chaim Kanievsky was asked how to succeed in Torah. He said: "Learn with simcha."',
  'Rav Elyashiv would learn in the same seat for decades; he said consistency builds greatness.',
  'The Chazon Ish said: "The main thing is not to lie to yourself."',
  'Rav Shach said: "A Jew must know that everything comes from Hashem."',
  'The Brisker Rav would analyze every word of the Rambam; precision in Torah was his path.',
  'Rav Moshe Feinstein was known for his humility; he would stand for any Jew with a question.',
  'Rav Soloveitchik said: "The covenant of fate and the covenant of destiny bind the Jew."',
  'The Lubavitcher Rebbe taught: "We must bring Mashiach with acts of goodness and kindness."',
  'Rav Nosson Tzvi Finkel would learn despite his illness; he said Torah gives strength.',
  'Rav Aharon Kotler built Lakewood on the idea that Torah is the foundation of the world.',
  'The Sfas Emes said: "Shabbos is the source of blessing for the entire week."',
  'Rav Yosef Chaim Sonnenfeld would not compromise on halacha even under pressure.',
  'The Ben Ish Chai wrote halacha and aggadah so that every Jew could learn.',
  'Rav Ovadia Yosef would answer every questioner; he said every Jew deserves an answer.',
  'The Maharal said: "Every Jew has a portion in the World to Come."',
  'Rav Elchanan Wasserman was killed al kiddush Hashem; his writings live on.',
  'The Arizal revealed that every word of Torah has infinite layers of meaning.',
  'Rav Yisrael Meir Kagan (Chofetz Chaim) wrote that guarding speech is the key to redemption.',
  'Rav Shimshon Raphael Hirsch said: "Torah im derech eretz—Torah with the way of the land."',
  'The Rogatchover said that every question has an answer in the Rambam.',
  'Rav Avraham Yitzchak Kook taught: "The pure righteous do not complain about the dark but add light."',
  'Rav Menachem Mendel of Kotzk said: "Where is G-d? Wherever you let Him in."',
  'The Maggid of Mezeritch said: "A little bit of light drives away much darkness."',
  'Rav Levi Yitzchak of Berditchev would find the good in every Jew.',
  'The Baal Shem Tov said: "From every human being there is something to learn."',
  'Rav Nachman of Breslov said: "The whole world is a very narrow bridge; the main thing is not to be afraid."',
  'Rav Pinchas of Koretz said: "G-d wants the heart."',
  'The holy Ohr HaChaim said that every letter of the Torah has 600,000 explanations.',
  'Rav Chaim Volozhiner said: "The soul is nourished by Torah."',
  'Rav Yosef Dov Soloveitchik (Beis HaLevi) would not speak lashon hara even about non-Jews.',
  'Rav Yitzchak Elchanan Spektor was known for his psak and his love for every Jew.',
  'The Netziv said that the generation of the desert was great because they followed Hashem into the wilderness.',
  'Rav Yisrael Salanter said: "The yetzer hara is clever; we must be cleverer."',
  'Rav Yosef Karo wrote the Shulchan Aruch so that halacha would be clear for all.',
  'The Rema added the Ashkenazi custom to the Shulchan Aruch; both are studied today.',
  'Rav Yehuda HaNasi compiled the Mishnah so that the Oral Torah would not be forgotten.',
  'Hillel would greet every person with a cheerful face.',
  'Shammai was strict in his service; both are the words of the living G-d.',
  'Rabbi Akiva said: "Love your fellow as yourself—this is a great principle of the Torah."',
  'Ben Azzai said: "This is the book of the generations of man—this is a greater principle."',
  'Rabbi Tarfon said: "The day is short and the work is great."',
  'Rabbi Eliezer said: "Let your friend\'s honor be as dear to you as your own."',
  'Rabbi Yehoshua said: "An evil eye, a bad inclination, and hatred of others remove a person from the world."',
  'Rabbi Yosi said: "Let your friend\'s property be as dear to you as your own."',
  'Rabbi Shimon said: "Say little and do much."',
  'Rabbi Elazar said: "Be diligent in the study of Torah, and know what to answer an apikores."',
  'Rabbi Yochanan ben Zakkai said: "If you have learned much Torah, do not take credit—for that you were created."',
  'Rabbi Chanina said: "I have learned much from my teachers, more from my colleagues, and most from my students."',
  'Elisha ben Avuyah said: "One who learns as a child is like ink written on new paper."',
  'Rabbi Meir said: "Whoever studies Torah for its own sake merits many things."',
  'Rabbi Nehorai said: "Exile yourself to a place of Torah."',
  'Rabbi Yannai said: "It is not in our hands to explain the tranquility of the wicked or the suffering of the righteous."',
  'Rabbi Matya ben Charash said: "Be first to greet every person."',
  'Rabbi Yaakov said: "This world is like a lobby before the World to Come; prepare yourself in the lobby."',
  'Rabbi Shimon ben Elazar said: "Do not appease your friend at the time of his anger."',
  'Rabbi Eliezer haKappar said: "Envy, desire, and honor remove a person from the world."',
  'Rabbi Chanina ben Dosa said: "One whose fear of sin precedes his wisdom—his wisdom endures."',
  'Rabbi Dostai said: "Sleep in the morning, wine at noon, and childish talk remove a person from the world."',
  'Rabbi Elazar haModa\'i said: "One who desecrates the sacred, who despises the festivals—he has no share in the World to Come."',
  'Rabbi Chanina said: "Prayer is the service of the heart."',
  'Rabbi Nechemia said: "Great is the mitzvah of tzedakah, for it hastens the redemption."',
  'Rabbi Yose said: "Let your friend\'s property be as dear to you as your own; prepare yourself to study Torah."',
  'Rabbi Yehuda said: "Be careful with the ruling—for they are the words of the living G-d."',
  'Rabbi Shimon said: "There are three crowns: the crown of Torah, the crown of kehunah, and the crown of kingship; the crown of a good name surpasses them all."',
  'Rabbi Nehorai said: "Exile yourself to a place of Torah, and do not say it will come after you."',
  'Rabbi Yosi said: "Let your friend\'s property be as dear to you as your own."',
  'Rabbi Elazar ben Shammua said: "Let the honor of your student be as dear to you as your own."',
  'Rabbi Yehuda said: "Be careful in teaching—for an error in teaching is considered intentional sin."',
  'Rabbi Shimon said: "There are three crowns: Torah, kehunah, and malchus; the crown of a good name rises above them."',
  'Rabbi Eliezer haKappar said: "Jealousy, lust, and honor drive a person from the world."',
  'Rabbi Chanina ben Chachinai said: "One who stays awake at night loses his portion in the World to Come."',
  'Rabbi Nechemyah said: "Great is tzedakah—it brings the redemption closer."',
  'Rabbi Yochanan ben Broka said: "Whoever desecrates the Name of Heaven in secret—they exact punishment from him in public."',
  'Rabbi Eliezer ben Yaakov said: "One who does one mitzvah acquires one advocate; one who does one sin acquires one accuser."',
  'Rabbi Yose ben Kisma said: "One day a man said to me: I will tell you where the Torah is. I said: My son, you have said the best thing."',
  'Rabbi Shimon ben Gamliel said: "On three things the world stands: on justice, on truth, and on peace."',
  'Rabbi Chanina Segan HaKohanim said: "Pray for the welfare of the government—for without its fear, a man would swallow his fellow alive."',
  'Rabbi Eliezer said: "Let your friend\'s honor be as dear to you as your own; and do not be easily angered."',
  'Rabbi Yehoshua said: "An evil eye, a bad inclination, and hatred of creatures remove a person from the world."',
  'Rabbi Yosi said: "Let your friend\'s property be as dear to you as your own; and prepare yourself for the study of Torah."',
  'Rabbi Shimon said: "Be careful with the reading of Shema and with the Amidah."',
  'Rabbi Elazar said: "Be diligent in the study of Torah, and know what to answer an apikores."',
  'Rabbi Yochanan ben Zakkai had five disciples; he said to them: "Go and see which is the good path to which a person should cling."',
  'Rabbi Eliezer said: "A good eye." Rabbi Yehoshua said: "A good friend." Rabbi Yosi said: "A good neighbor." Rabbi Shimon said: "One who sees the consequences." Rabbi Elazar said: "A good heart."',
  'He said to them: "I prefer the words of Elazar ben Arach, for his words include all of yours."',
  'He said to them: "Go and see which is the bad path that a person should avoid."',
  'Rabbi Eliezer said: "An evil eye." Rabbi Yehoshua said: "A bad friend." Rabbi Yosi said: "A bad neighbor." Rabbi Shimon said: "One who borrows and does not repay." Rabbi Elazar said: "A bad heart."',
  'He said to them: "I prefer the words of Elazar ben Arach, for his words include all of yours."',
  'Rabbi Akiva said: "Everything is given on pledge, and a net is spread over all the living."',
  'Ben Hei Hei said: "According to the pain is the gain."',
  'Rabbi Chanina ben Akavia said: "The Holy One desired to merit Israel; therefore He gave them Torah and mitzvos in abundance."',
  'Rabbi Elazar said: "Be diligent in the study of Torah, and know what to answer an apikores; and know before Whom you toil."',
  'Rabbi Tarfon said: "The day is short, the work is great, the workers are lazy, the reward is great, and the Master of the house is pressing."',
  'He used to say: "It is not your duty to finish the work, but neither are you free to desist from it."',
  'Rabbi Yosi said: "Let your friend\'s property be as dear to you as your own; and prepare yourself for the study of Torah."',
  'Rabbi Shimon said: "The correct path is the one that is an honor to the person who follows it and brings him honor from others."',
  'Rabbi Elazar said: "Let the honor of your student be as dear to you as your own, and the honor of your friend as the fear of your teacher."',
  'Rabbi Yehuda said: "Be careful in teaching, for an error in teaching is considered an intentional sin."',
  'Rabbi Shimon said: "There are three crowns: the crown of Torah, the crown of kehunah, and the crown of malchus; but the crown of a good name rises above them all."',
  'Rabbi Nehorai said: "Exile yourself to a place of Torah, and do not say that it will come after you."',
  'Rabbi Yannai said: "It is not in our hands to explain either the tranquility of the wicked or the suffering of the righteous."',
  'Rabbi Matya ben Charash said: "Be first to greet every person, and be a tail to lions rather than a head to foxes."',
  'Rabbi Yaakov said: "This world is like a lobby before the World to Come; prepare yourself in the lobby so that you may enter the banquet hall."',
  'Rabbi Shimon ben Elazar said: "Do not appease your friend at the time of his anger; do not comfort him while his dead lies before him."',
  'Rabbi Elazar haKappar said: "Envy, desire, and honor remove a person from the world."',
  'Rabbi Chanina ben Dosa said: "One whose fear of sin precedes his wisdom—his wisdom endures; but one whose wisdom precedes his fear of sin—his wisdom does not endure."',
  'Rabbi Dostai ben Yannai said: "Morning sleep, midday wine, childish talk, and sitting in the assemblies of the ignorant remove a person from the world."',
  'Rabbi Elazar haModa\'i said: "One who desecrates the sacred, who despises the festivals, who puts his fellow to shame in public—he has no share in the World to Come."',
  'Rabbi Chanina Segan HaKohanim said: "Pray for the welfare of the government—for were it not for the fear of it, a man would swallow his fellow alive."',
  'Rabbi Nechemyah said: "Great is the mitzvah of tzedakah, for it hastens the redemption."',
  'Rabbi Yochanan ben Broka said: "Whoever desecrates the Name of Heaven in secret—they exact punishment from him in public."',
  'Rabbi Eliezer ben Yaakov said: "One who does one mitzvah acquires one advocate for himself; one who does one sin acquires one accuser."',
  'Rabbi Yose ben Kisma said: "One day I was walking and a man met me and greeted me... I said to him: My son, from where do you come? He said: From a great city of sages. I said: My son, if you dwell there, I will make you live in the World to Come."',
  'Rabbi Shimon ben Gamliel said: "On three things the world stands: on justice, on truth, and on peace."',
  'Rabbi Chanina said: "I have learned much from my teachers, and from my colleagues more than from my teachers, and from my students more than from all of them."',
  'Rabbi Elazar said: "Be diligent in the study of Torah, and know what to answer an apikores; and know before Whom you toil, and Who is your Employer who will pay you the reward of your labor."',
  'Rabbi Tarfon said: "The day is short, the work is great, the workers are lazy, the reward is great, and the Master of the house is pressing."',
  'Rabbi Akiva said: "Everything is given on pledge, and a net is spread over all the living; the shop is open, the Shopkeeper extends credit, the ledger is open, and the hand writes."',
  'Ben Azzai said: "Run to fulfill a light mitzvah as a heavy one, and flee from transgression; for one mitzvah leads to another, and one transgression leads to another."',
];

export const JEWISH_HISTORY_ON_THIS_DAY: string[] = [
  'On this day in Jewish history, our people chose Torah and said "Naaseh v\'nishma."',
  'Generations kept the flame of Torah alive through learning and practice.',
  'Today we continue the chain from Har Sinai to the next generation.',
  'Jewish history is full of renewal—every day we can renew our commitment.',
  'On days like this, Jews everywhere opened a sefer and learned.',
  'Our calendar is rich with days of meaning; today is what we make it.',
  'Each day is a chance to add a link in the chain of mesorah.',
  'Har Sinai: the entire nation stood as one to receive the Torah.',
  'The Mishkan was built in the wilderness; the Shechinah dwelled among Israel.',
  'The first Beis HaMikdash stood in Jerusalem for 410 years.',
  'The second Beis HaMikdash stood for 420 years until the Roman destruction.',
  'The Anshei Knesses HaGedolah established tefillah and the structure of Torah she\'be\'al peh.',
  'The Tannaim compiled the Mishnah; Rabbi Yehuda HaNasi sealed it.',
  'The Amoraim in Bavel and Eretz Yisrael produced the Gemara.',
  'The Geonim led the academies of Sura and Pumbedita for centuries.',
  'Rashi wrote his commentary on Torah and Talmud in France.',
  'The Tosafists built on Rashi and sharpened every sugya.',
  'The Rambam wrote the Mishneh Torah and the Guide; his influence spans the world.',
  'The Zohar was revealed; kabbalah became a path for the many.',
  'The Shulchan Aruch was written; halacha was codified for daily life.',
  'The Baal Shem Tov revealed Chassidus; joy and love entered avodah.',
  'The Vilna Gaon led the opposition to Chassidus and deepened pilpul.',
  'Yeshivos grew in Lithuania; the mussar movement refined character.',
  'Chabad spread the inner dimension of Torah to every Jew.',
  'The State of Israel was declared; the ingathering of exiles began.',
  'Jews have kept Shabbos for over 3,300 years.',
  'Pesach has been observed since the Exodus from Egypt.',
  'Rosh Hashanah and Yom Kippur have framed the year since Sinai.',
  'Sukkos recalls the clouds of glory and the harvest.',
  'Chanukah recalls the victory of the Chashmonaim and the miracle of the oil.',
  'Purim recalls the salvation in the days of Mordechai and Esther.',
  'The Omer links Pesach to Shavuos—freedom to responsibility.',
  'Tisha B\'Av commemorates the destruction of both Temples.',
  'The four fasts recall stages of the churban.',
  'Rosh Chodesh has been sanctified by beis din and then by the fixed calendar.',
  'Daf Yomi unites Jews worldwide in one page of Gemara each day.',
  'Mishna Yomi and Nach Yomi bring daily study to thousands.',
  'The Rambam\'s daily study (3 chapters or 1) is learned by many.',
  'Tehillim has been recited for comfort and prayer for millennia.',
  'The siddur was fixed by the Anshei Knesses HaGedolah.',
  'Piyutim were added over the ages for the Yamim Noraim and festivals.',
  'Jewish communities have built shuls, yeshivos, and chesed organizations.',
  'Tzedakah has been a pillar of Jewish life in every generation.',
  'Bikur cholim and gemilus chasadim have defined Jewish society.',
  'Hachnasas orchim has been a mark of Avraham\'s children.',
  'Kavod haTorah has preserved the role of the talmid chacham.',
  'Chinuch has been the priority of every Jewish parent.',
  'The mesorah of family and community has kept Judaism alive.',
  'In every land of exile, Jews built kehillos and kept the covenant.',
  'Persecution did not end Jewish learning; it deepened commitment.',
  'The Holocaust destroyed communities but not the spirit of Torah.',
  'The rebirth of Israel gave a home to the Jewish people.',
  'Today Jews learn Torah in every corner of the world.',
  'Technology has made Torah accessible to all who seek it.',
  'The chain of semichah and mesorah continues unbroken.',
  'Every day a Jew puts on tefillin, the covenant is renewed.',
  'Every Shabbos the world is reminded of creation and redemption.',
  'Every Yom Tov we relive the events that shaped our nation.',
  'The parsha of the week has guided Jews for thousands of years.',
  'Daf Yomi has created a global chaburah of Talmud study.',
  'Women\'s learning has flourished in seminaries and shiurim.',
  'Kiruv has brought many Jews back to their heritage.',
  'Jewish music and art have expressed our soul through the ages.',
  'Jewish names and Hebrew have been preserved across generations.',
  'Kashrus has kept the Jewish home distinct and holy.',
  'Taharas hamishpacha has been the foundation of the Jewish family.',
  'The brachos we say today are the same as those of our ancestors.',
  'The words of the Amidah have been said for over 2,000 years.',
  'Kiddush and Havdalah have marked the boundaries of Shabbos.',
  'The Pesach Seder has been passed from parent to child.',
  'The shofar has been blown on Rosh Hashanah since the Torah was given.',
  'The lulav and esrog have been taken on Sukkos every year.',
  'The menorah has been lit on Chanukah since the days of the Chashmonaim.',
  'The Megillah has been read on Purim in every generation.',
  'Jewish history is not only the past—it is the present and future.',
  'Every Jew who learns today adds to the chain.',
  'Every mitzvah done today strengthens the world.',
  'The Beis HaMikdash will be rebuilt; we pray for it every day.',
  'Mashiach will come; we await him every day.',
  'The resurrection of the dead and the World to Come are our hope.',
  'Hashem is One; His name is One; we are His people.',
  'Am Yisrael Chai—the people of Israel live.',
  'L\'shanah haba\'ah b\'Yerushalayim—next year in Jerusalem.',
  'Today you can open a sefer and join the chain.',
  'Today you can do a mitzvah and change the world.',
  'Today you can daven and connect to the Infinite.',
  'Today you can give tzedakah and partner with Hashem.',
  'Today you can learn one line of Torah and add light.',
  'Today you can guard your speech and bring peace.',
  'Today you can judge others favorably and bring mercy.',
  'Today you can repent and draw close to Hashem.',
  'Today you can choose life and blessing.',
  'Jewish history is written every day by every Jew.',
  'Your actions today become part of that history.',
  'The gedolim of the past learned and taught; we follow in their path.',
  'The simple Jew who said Shema with kavanah is remembered in Heaven.',
  'Every candle lit on Chanukah adds to the light.',
  'Every word of Tehillim said for another is a merit.',
  'Every act of chesed is a brick in the future redemption.',
  'The Jewish people have survived every empire; we will endure.',
  'Torah is eternal; those who learn it share in that eternity.',
  'Today is a good day to add your link to the chain.',
  'Be the Jew who learns, who prays, who gives, who cares.',
  'The world was created for Torah and for those who keep it.',
  'You are part of the story; make your chapter count.',
  'From generation to generation we pass the torch.',
  'L\'dor vador—from generation to generation—we are one people.',
  'Today, as on every day, the Jewish people choose life.',
  'Zachor—remember—and act. That is Jewish history.',
  'The past inspires; the present demands; the future awaits.',
  'One hundred days of learning, one hundred days of growth.',
];

/** One-line summary per parsha (54 parshios). Index by parsha name (English) or use order. */
export const PARSHA_SUMMARIES: Record<string, string> = {
  'Bereshit': 'Creation, the first humans, and the early generations.',
  'Noach': 'The flood, Noach\'s ark, and the tower of Bavel.',
  'Lech Lecha': 'Avraham leaves his home and receives the covenant.',
  'Vayeira': 'The angels, Sodom, and the akeidah.',
  'Chayei Sarah': 'Sarah\'s passing and Yitzchak\'s marriage to Rivkah.',
  'Toldos': 'Yaakov and Esav; the birthright and the brachos.',
  'Vayeitzei': 'Yaakov\'s dream, Lavan, and building a family.',
  'Vayishlach': 'Yaakov meets Esav and settles in Canaan.',
  'Vayeishev': 'Yosef\'s dreams, the pit, and Egypt.',
  'Miketz': 'Pharaoh\'s dreams and Yosef becomes viceroy.',
  'Vayigash': 'Yehuda pleads; Yaakov\'s family goes down to Egypt.',
  'Vayechi': 'Yaakov\'s brachos and his passing in Egypt.',
  'Shemos': 'Slavery in Egypt and the birth of Moshe.',
  'Va\'eira': 'The first plagues and "I will take you out."',
  'Bo': 'The last plagues and the Exodus.',
  'Beshalach': 'The sea splits; manna and the well.',
  'Yisro': 'Yisro\'s advice and the giving of the Torah.',
  'Mishpatim': 'Laws of damages, slaves, and justice.',
  'Terumah': 'The command to build the Mishkan.',
  'Tetzaveh': 'The kohen\'s garments and the menorah.',
  'Ki Sisa': 'The half-shekel, the eigel, and the second luchos.',
  'Vayakhel': 'Building the Mishkan; Shabbos and the work.',
  'Pekudei': 'The Mishkan is completed and erected.',
  'Vayikra': 'Korbanos: olah, mincha, and peace offerings.',
  'Tzav': 'Laws of the korbanos and the kohanim.',
  'Shemini': 'The Mishkan is dedicated; the death of Nadav and Avihu.',
  'Tazria': 'Laws of tzaraas and purity.',
  'Metzora': 'Purification from tzaraas and the house.',
  'Achrei Mos': 'The Yom Kippur avodah and arayos.',
  'Kedoshim': '"Be holy"—many mitzvos between person and Hashem.',
  'Emor': 'Laws of kohanim, the holidays, and the blasphemer.',
  'Behar': 'Shemitta and yovel; the land belongs to Hashem.',
  'Bechukosai': 'Blessings, rebuke, and vows.',
  'Bamidbar': 'Counting the tribes and the camp.',
  'Nasso': 'The nazir, sotah, and the tribal offerings.',
  'Beha\'aloscha': 'The menorah, the second Pesach, and the cloud.',
  'Shelach': 'The spies and the decree of the midbar.',
  'Korach': 'Korach\'s rebellion and the earth opens.',
  'Chukas': 'The parah adumah and the death of Miriam and Aharon.',
  'Balak': 'Bilaam is hired to curse; the donkey speaks.',
  'Pinchas': 'Pinchas\' zeal; the census and the festivals.',
  'Matos': 'Vows and the war with Midian.',
  'Masei': 'The journeys and the borders of the land.',
  'Devarim': 'Moshe begins his farewell; review of the journey.',
  'Va\'eschanan': 'The Aseres Hadibros and Shema.',
  'Eikev': 'Reward for mitzvos and the second paragraph of Shema.',
  'Re\'eh': 'The choice of bracha; the central place of avodah.',
  'Shoftim': 'Judges, king, and the laws of war.',
  'Ki Seitzei': 'Many mitzvos: marriage, war, and justice.',
  'Ki Savo': 'Bikkurim, the viduy, and the brachos and kelalos.',
  'Nitzavim': 'The covenant and "choose life."',
  'Vayeilech': 'Moshe gives the sefer Torah to the Leviim.',
  'Ha\'azinu': 'The song of Ha\'azinu.',
  'V\'Zos HaBracha': 'Moshe\'s bracha and his passing.',
};

export const AFFIRMATIONS: string[] = [
  'I am blessed.',
  'Today I grow.',
  'Hashem is with me.',
  'I can do hard things.',
  'I am worthy of love.',
  'I choose life and bracha.',
  'My actions matter.',
  'I am created in the image of G-d.',
  'Today I will learn something new.',
  'I choose to see the good.',
  'I am part of something eternal.',
  'My tefillos are heard.',
  'I can make a difference.',
  'I am grateful for this day.',
  'I will guard my speech today.',
  'I will do one act of chesed today.',
  'I am strong enough to grow.',
  'I choose trust over worry.',
  'I am worthy of peace.',
  'Today I will add light.',
  'I am not alone.',
  'I can start again.',
  'My efforts count.',
  'I choose to judge others favorably.',
  'I will learn one thing today.',
  'I am part of Am Yisrael.',
  'I will daven with kavanah.',
  'I can overcome my yetzer hara.',
  'I am deserving of kindness.',
  'Today I will give tzedakah.',
  'I will honor my parents.',
  'I choose humility.',
  'I am capable of change.',
  'My soul is pure.',
  'I will make today meaningful.',
  'I am connected to the chain of tradition.',
  'I can face today\'s challenges.',
  'I choose gratitude.',
  'I will speak with care.',
  'I am loved by Hashem.',
  'Today I will do a mitzvah.',
  'I can be patient.',
  'I am building my portion in the World to Come.',
  'I will not give up.',
  'I choose to forgive.',
  'I am a work in progress.',
  'Today I will help someone.',
  'I can control my reactions.',
  'I am part of the redemption.',
  'I will remember what matters.',
  'I choose hope.',
  'I am enough.',
  'Today I will guard my eyes.',
  'I can learn from everyone.',
  'I am responsible for my choices.',
  'I will stand for truth.',
  'I choose to build, not destroy.',
  'I am here for a reason.',
  'Today I will be present.',
  'I can let go of what I cannot control.',
  'I am worthy of rest on Shabbos.',
  'I will celebrate the good.',
  'I choose to respond with love.',
  'I am a child of Avraham, Yitzchak, and Yaakov.',
  'Today I will open a sefer.',
  'I can be the change.',
  'I am part of the covenant.',
  'I will pray for others.',
  'I choose to see the Divine in others.',
  'I am capable of greatness.',
  'Today I will be kind to myself.',
  'I can finish what I start.',
  'I am deserving of Shalom.',
  'I will remember the Exodus today.',
  'I choose to learn from the past.',
  'I am a link in the chain.',
  'Today I will say thank you.',
  'I can make peace.',
  'I am created for purpose.',
  'I will not speak lashon hara.',
  'I choose to believe in tomorrow.',
  'I am worthy of the Torah.',
  'Today I will take one step.',
  'I can inspire others.',
  'I am part of the story.',
  'I will keep going.',
  'I choose to add holiness.',
  'I am grateful for my neshama.',
  'Today I will be honest.',
  'I can accept myself.',
  'I am deserving of joy.',
  'I will seek wisdom.',
  'I choose to build my character.',
  'I am never too far to return.',
  'Today I will connect.',
  'I can be a light.',
  'I am part of the solution.',
  'I will honor the day.',
  'I choose life today.',
  'I am blessed to be a Jew.',
  'Today I will remember Har Sinai.',
  'I can fulfill my potential.',
  'I am worthy of redemption.',
  'I will do my part.',
  'I choose to hope for Mashiach.',
  'I am never alone in the journey.',
  'Today I will trust the process.',
  'I can grow from difficulty.',
  'I am a vessel for light.',
  'I will make my corner of the world better.',
  'I choose to believe in myself.',
  'I am here; I am now; I am enough.',
];

/** Get content keyed by day of week (0–6). Kept for compatibility; prefer getByDay100 for 100-day cycle. */
export function getByDayOfWeek<T>(arr: T[]): T {
  return getByDay100(arr);
}

/** Real Chumash verses and themes (100) for the daily Chumash widget. */
export const CHUMASH_DAILY: string[] = [
  'In the beginning G-d created the heaven and the earth. (Bereshis 1:1)',
  'And G-d said: Let there be light. And there was light. (Bereshis 1:3)',
  'And G-d created man in His image. (Bereshis 1:27)',
  'And G-d blessed the seventh day and sanctified it. (Bereshis 2:3)',
  'Therefore shall a man leave his father and his mother and cleave to his wife. (Bereshis 2:24)',
  'And Noach found favor in the eyes of Hashem. (Bereshis 6:8)',
  'Go forth from your land, your birthplace, and your father\'s house. (Bereshis 12:1)',
  'And he believed in Hashem, and He counted it to him as righteousness. (Bereshis 15:6)',
  'Shall the Judge of all the earth not do justice? (Bereshis 18:25)',
  'And Avraham arose early in the morning and saddled his donkey. (Bereshis 22:3)',
  'G-d will see to the lamb for the offering. (Bereshis 22:8)',
  'And they said: Naaseh v\'nishma—we will do and we will hear. (Shemos 24:7)',
  'I am Hashem your G-d who brought you out of the land of Egypt. (Shemos 20:2)',
  'You shall have no other gods before Me. (Shemos 20:3)',
  'Remember the Sabbath day to keep it holy. (Shemos 20:8)',
  'Honor your father and your mother. (Shemos 20:12)',
  'You shall love your fellow as yourself. (Vayikra 19:18)',
  'You shall be holy, for I Hashem your G-d am holy. (Vayikra 19:2)',
  'And you shall love Hashem your G-d with all your heart. (Devarim 6:5)',
  'And you shall teach them diligently to your children. (Devarim 6:7)',
  'For the mitzvah is a lamp and the Torah is light. (Mishlei 6:23)',
  'Choose life, that you and your offspring may live. (Devarim 30:19)',
  'Justice, justice shall you pursue. (Devarim 16:20)',
  'Man does not live by bread alone. (Devarim 8:3)',
  'The secret things belong to Hashem our G-d. (Devarim 29:28)',
  'And you shall know today and set upon your heart that Hashem is G-d. (Devarim 4:39)',
  'And now, Israel, what does Hashem your G-d require of you? Only to fear Him. (Devarim 10:12)',
  'Circumcise the foreskin of your heart. (Devarim 10:16)',
  'For Hashem your G-d is the G-d of gods and the Lord of lords. (Devarim 10:17)',
  'He executes justice for the fatherless and the widow. (Devarim 10:18)',
  'Love the ger, for you were gerim in the land of Egypt. (Devarim 10:19)',
  'You shall fear Hashem your G-d; Him you shall serve. (Devarim 10:20)',
  'And you shall eat and be satisfied, and bless Hashem your G-d. (Devarim 8:10)',
  'Beware lest you forget Hashem your G-d. (Devarim 8:11)',
  'And you shall remember the entire way that Hashem your G-d led you. (Devarim 8:2)',
  'So that He might make you know that man does not live by bread alone. (Devarim 8:3)',
  'A land that Hashem your G-d cares for. (Devarim 11:12)',
  'Place these words upon your heart and upon your soul. (Devarim 11:18)',
  'Write them on the doorposts of your house and on your gates. (Devarim 11:20)',
  'For the matter is very near to you, in your mouth and in your heart. (Devarim 30:14)',
  'See, I have set before you today life and good, death and evil. (Devarim 30:15)',
  'Therefore choose life. (Devarim 30:19)',
  'Loving Hashem your G-d, obeying His voice, and holding fast to Him. (Devarim 30:20)',
  'For He is your life and length of days. (Devarim 30:20)',
  'The Torah which Moshe commanded is the heritage of the congregation of Yaakov. (Devarim 33:4)',
  'Happy are you, Israel! Who is like you, a people saved by Hashem? (Devarim 33:29)',
  'The eternal G-d is a dwelling place, and underneath are the everlasting arms. (Devarim 33:27)',
  'And He said: I will hide My face from them. (Devarim 31:18)',
  'For it is not an empty thing for you; it is your life. (Devarim 32:47)',
  'Give ear, O heavens, and I will speak. (Devarim 32:1)',
  'The Rock, His work is perfect, for all His ways are justice. (Devarim 32:4)',
  'Is He not your Father who created you? (Devarim 32:6)',
  'Remember the days of old; consider the years of many generations. (Devarim 32:7)',
  'He found him in a desert land. (Devarim 32:10)',
  'He encompassed him, He instructed him, He guarded him like the apple of His eye. (Devarim 32:10)',
  'As an eagle stirs up its nest, flutters over its young. (Devarim 32:11)',
  'Hashem alone did lead him. (Devarim 32:12)',
  'He made him ride on the high places of the earth. (Devarim 32:13)',
  'And he ate the produce of the field. (Devarim 32:13)',
  'And he suckled honey from the rock. (Devarim 32:13)',
  'But Yeshurun grew fat and kicked. (Devarim 32:15)',
  'They have corrupted themselves; they are not His children. (Devarim 32:5)',
  'Do you thus requite Hashem, O foolish and unwise people? (Devarim 32:6)',
  'Is He not your Father who has acquired you? (Devarim 32:6)',
  'Remember the days of old. (Devarim 32:7)',
  'When the Most High gave to the nations their inheritance. (Devarim 32:8)',
  'For Hashem\'s portion is His people; Yaakov is the lot of His inheritance. (Devarim 32:9)',
  'He found him in a desert land, and in the waste. (Devarim 32:10)',
  'He instructed him, He kept him as the apple of His eye. (Devarim 32:10)',
  'As an eagle that stirs up its nest, that hovers over its young. (Devarim 32:11)',
  'Hashem alone did lead him, and there was no strange god with him. (Devarim 32:12)',
  'He made him ride on the high places of the earth. (Devarim 32:13)',
  'And he ate the increase of the field. (Devarim 32:13)',
  'And he made him suck honey out of the rock. (Devarim 32:13)',
  'And oil out of the flinty rock. (Devarim 32:13)',
  'Curds of kine, and milk of sheep. (Devarim 32:14)',
  'With fat of lambs, and rams of the breed of Bashan. (Devarim 32:14)',
  'And goats, with the finest of wheat. (Devarim 32:14)',
  'And of the blood of the grape you drank wine. (Devarim 32:14)',
  'But Yeshurun waxed fat, and kicked. (Devarim 32:15)',
  'You are waxed fat, you are grown thick. (Devarim 32:15)',
  'And he forsook G-d who made him. (Devarim 32:15)',
  'And contemned the Rock of his salvation. (Devarim 32:15)',
  'They provoked Him with strange gods. (Devarim 32:16)',
  'With abominations they provoked Him to anger. (Devarim 32:16)',
  'They sacrificed to demons, no-gods. (Devarim 32:17)',
  'Gods they knew not, new ones that came up of late. (Devarim 32:17)',
  'Of the Rock that begot you you are unmindful. (Devarim 32:18)',
  'And have forgotten G-d who gave you birth. (Devarim 32:18)',
  'And Hashem saw, and spurned. (Devarim 32:19)',
  'Because of the provocation of His sons and His daughters. (Devarim 32:19)',
  'And He said: I will hide My face from them. (Devarim 31:18)',
  'I will see what their end shall be. (Devarim 32:20)',
  'For they are a generation of reversals. (Devarim 32:20)',
  'Children in whom is no faithfulness. (Devarim 32:20)',
  'They have roused Me to jealousy with a no-god. (Devarim 32:21)',
  'They have provoked Me with their vanities. (Devarim 32:21)',
  'And I will rouse them to jealousy with a no-people. (Devarim 32:21)',
  'With a foolish nation I will provoke them. (Devarim 32:21)',
  'For a fire is kindled in My nostril. (Devarim 32:22)',
  'And burns unto the depths of the netherworld. (Devarim 32:22)',
  'And devours the earth with her produce. (Devarim 32:22)',
  'And sets ablaze the foundations of the mountains. (Devarim 32:22)',
  'I will heap evils upon them. (Devarim 32:23)',
  'I will spend My arrows upon them. (Devarim 32:23)',
  'They shall be wasted with hunger. (Devarim 32:24)',
  'And devoured with burning heat. (Devarim 32:24)',
  'And bitter destruction. (Devarim 32:24)',
  'The teeth of beasts will I send upon them. (Devarim 32:24)',
  'With the venom of crawling things of the dust. (Devarim 32:24)',
  'Without, the sword shall bereave. (Devarim 32:25)',
  'And in the chambers, terror. (Devarim 32:25)',
  'Both the young man and the virgin. (Devarim 32:25)',
  'The suckling with the man of gray hairs. (Devarim 32:25)',
  'I would have said: I will scatter them abroad. (Devarim 32:26)',
  'I will make the remembrance of them to cease from among men. (Devarim 32:26)',
  'Were it not that I dreaded the provocation of the enemy. (Devarim 32:27)',
  'Lest their adversaries should misdeem. (Devarim 32:27)',
  'Lest they should say: Our hand is exalted. (Devarim 32:27)',
  'And Hashem has not done all this. (Devarim 32:27)',
  'For they are a nation void of counsel. (Devarim 32:28)',
  'And there is no understanding in them. (Devarim 32:28)',
  'O that they were wise, that they understood this. (Devarim 32:29)',
  'That they would consider their latter end. (Devarim 32:29)',
  'How could one chase a thousand? (Devarim 32:30)',
  'And two put ten thousand to flight? (Devarim 32:30)',
  'Except their Rock had sold them. (Devarim 32:30)',
  'And Hashem had delivered them up. (Devarim 32:30)',
  'For their rock is not as our Rock. (Devarim 32:31)',
  'Our enemies themselves being judges. (Devarim 32:31)',
  'For their vine is of the vine of Sodom. (Devarim 32:32)',
  'And of the fields of Gomorrah. (Devarim 32:32)',
  'Their grapes are grapes of gall. (Devarim 32:32)',
  'Their clusters are bitter. (Devarim 32:32)',
  'Their wine is the venom of serpents. (Devarim 32:33)',
  'And the cruel poison of asps. (Devarim 32:33)',
  'Is not this laid up in store with Me? (Devarim 32:34)',
  'Sealed up in My treasuries? (Devarim 32:34)',
  'Vengeance is Mine, and recompense. (Devarim 32:35)',
  'Their foot shall slide in due time. (Devarim 32:35)',
  'For the day of their calamity is at hand. (Devarim 32:35)',
  'And the things that are to come upon them shall make haste. (Devarim 32:35)',
  'For Hashem will judge His people. (Devarim 32:36)',
  'And repent Himself for His servants. (Devarim 32:36)',
  'When He sees that their power is gone. (Devarim 32:36)',
  'And there is none remaining, shut up or left at large. (Devarim 32:36)',
  'And He will say: Where are their gods? (Devarim 32:37)',
  'The rock in whom they trusted. (Devarim 32:37)',
  'See now that I, even I, am He. (Devarim 32:39)',
  'And there is no god with Me. (Devarim 32:39)',
  'I kill, and I make alive. (Devarim 32:39)',
  'I have wounded, and I heal. (Devarim 32:39)',
  'And there is none that can deliver out of My hand. (Devarim 32:39)',
  'For I lift up My hand to heaven. (Devarim 32:40)',
  'And say: As I live forever. (Devarim 32:40)',
  'If I whet My glittering sword. (Devarim 32:41)',
  'And My hand take hold on judgment. (Devarim 32:41)',
  'I will render vengeance to Mine adversaries. (Devarim 32:41)',
  'And will repay them that hate Me. (Devarim 32:41)',
  'I will make Mine arrows drunk with blood. (Devarim 32:42)',
  'And My sword shall devour flesh. (Devarim 32:42)',
  'Rejoice, O nations, with His people. (Devarim 32:43)',
  'For He will avenge the blood of His servants. (Devarim 32:43)',
  'And will render vengeance to His adversaries. (Devarim 32:43)',
  'And will make expiation for the land of His people. (Devarim 32:43)',
  'And Moshe came and spoke all the words of this song in the ears of the people. (Devarim 32:44)',
  'And he said unto them: Set your heart unto all the words. (Devarim 32:46)',
  'For it is not a vain thing for you; because it is your life. (Devarim 32:47)',
  'And through this word you shall prolong your days. (Devarim 32:47)',
  'And this is the blessing with which Moshe the man of G-d blessed the children of Israel. (Devarim 33:1)',
  'The eternal G-d is a dwelling place. (Devarim 33:27)',
  'And underneath are the everlasting arms. (Devarim 33:27)',
  'Happy are you, Israel! Who is like you? (Devarim 33:29)',
  'A people saved by Hashem. (Devarim 33:29)',
  'The shield of your help. (Devarim 33:29)',
  'And the sword of your triumph. (Devarim 33:29)',
];

/** Real Zohar and Chassidus teachings (100) for the Zohar/Chassidus widget. */
export const ZOHAR_CHASSIDUS: string[] = [
  'The world stands on three things: Torah, avodah, and gemilus chasadim. (Pirkei Avos)',
  'A little bit of light drives away much darkness. (Maggid of Mezeritch)',
  'In everything there is a lesson in serving Hashem. (Baal Shem Tov)',
  'Where is G-d? Wherever you let Him in. (Kotzker Rebbe)',
  'The pure righteous do not complain about the dark but add light. (Rav Kook)',
  'G-d wants the heart. (Tanna)',
  'The soul is nourished by Torah. (Rav Chaim Volozhiner)',
  'We must bring Mashiach with acts of goodness and kindness. (Lubavitcher Rebbe)',
  'The main thing is not to be afraid. (Rav Nachman of Breslov)',
  'From every human being there is something to learn. (Baal Shem Tov)',
  'The Holy One desired to merit Israel; therefore He gave them Torah and mitzvos. (Pirkei Avos)',
  'Turn it and turn it, for everything is in it. (Pirkei Avos on Torah)',
  'Great is Torah for it gives life to those who do it. (Pirkei Avos)',
  'The day is short and the work is great. (Pirkei Avos)',
  'It is not upon you to finish the work, nor may you desist from it. (Pirkei Avos)',
  'Who is wise? One who learns from every person. (Pirkei Avos)',
  'Who is strong? One who conquers his inclination. (Pirkei Avos)',
  'Who is rich? One who is satisfied with his portion. (Pirkei Avos)',
  'Say little and do much. (Pirkei Avos)',
  'Greet every person with a cheerful face. (Pirkei Avos)',
  'That which is hateful to you, do not do to your fellow. (Hillel)',
  'What is mine is yours and what is yours is yours—that is a chassid. (Pirkei Avos)',
  'Let your friend\'s honor be as dear to you as your own. (Pirkei Avos)',
  'Do not be easily angered. (Pirkei Avos)',
  'Repent one day before your death. (Pirkei Avos)',
  'Know what is above you: an eye that sees, an ear that hears. (Pirkei Avos)',
  'All is foreseen, yet free will is given. (Pirkei Avos)',
  'The reward of a mitzvah is a mitzvah. (Pirkei Avos)',
  'Words that come from the heart enter the heart. (Chassidus)',
  'A person is led on the path he wishes to follow. (Pirkei Avos)',
  'The Zohar: The Holy One and the Assembly of Israel are one. (Zohar)',
  'The Zohar: There is no place empty of Him. (Zohar)',
  'The Zohar: The Torah is the name of the Holy One. (Zohar)',
  'The Zohar: When Israel is below, the Holy One is crowned above. (Zohar)',
  'The Zohar: The lower world is a mirror of the upper world. (Zohar)',
  'The Zohar: The soul comes from a high place. (Zohar)',
  'The Zohar: Shabbos is the day of the soul. (Zohar)',
  'The Zohar: Every letter of the Torah has worlds and lights. (Zohar)',
  'The Zohar: Tzedakah sustains the world. (Zohar)',
  'The Zohar: Prayer unites the upper and lower. (Zohar)',
  'Chassidus: Serve Hashem with joy. (Tehillim)',
  'Chassidus: The world was created for the sake of the tzaddik. (Talmud)',
  'Chassidus: A tzaddik lives by his faith. (Chabakuk)',
  'Chassidus: The righteous one is the foundation of the world. (Mishlei)',
  'Chassidus: One hour of repentance and good deeds in this world is better than all of the World to Come. (Pirkei Avos)',
  'Chassidus: The Holy One desires the heart. (Talmud)',
  'Chassidus: Let all your deeds be for the sake of Heaven. (Pirkei Avos)',
  'Chassidus: In the place where penitents stand, the completely righteous cannot stand. (Talmud)',
  'Chassidus: The Shechinah dwells with every person in accordance with his deeds. (Midrash)',
  'Chassidus: Every Jew has a portion in the World to Come. (Mishnah)',
  'Chassidus: The soul you have given me is pure. (Morning prayer)',
  'Chassidus: I place Hashem before me always. (Tehillim)',
  'Chassidus: Hashem is close to all who call to Him in truth. (Tehillim)',
  'Chassidus: Taste and see that Hashem is good. (Tehillim)',
  'Chassidus: One thing I asked of Hashem—that I may dwell in His house. (Tehillim)',
  'Chassidus: The heavens declare the glory of G-d. (Tehillim)',
  'Chassidus: Hashem is my shepherd; I shall not want. (Tehillim)',
  'Chassidus: Even when I walk in the valley of the shadow of death, I will fear no evil. (Tehillim)',
  'Chassidus: Your rod and Your staff—they comfort me. (Tehillim)',
  'Chassidus: Goodness and mercy shall follow me all the days of my life. (Tehillim)',
  'Chassidus: And I shall dwell in the house of Hashem forever. (Tehillim)',
  'Chassidus: Hashem is my light and my salvation. (Tehillim)',
  'Chassidus: One thing I asked of Hashem, that I will seek—to dwell in the house of Hashem. (Tehillim)',
  'Chassidus: Wait for Hashem; be strong and let your heart take courage. (Tehillim)',
  'Chassidus: Hashem is the strength of my life. (Tehillim)',
  'Chassidus: Trust in Hashem forever, for in Hashem is everlasting strength. (Yeshayahu)',
  'Chassidus: Those who wait for Hashem shall renew their strength. (Yeshayahu)',
  'Chassidus: They shall mount up with wings as eagles. (Yeshayahu)',
  'Chassidus: They shall run and not be weary; they shall walk and not faint. (Yeshayahu)',
  'Chassidus: The whole earth is full of His glory. (Yeshayahu)',
  'Chassidus: Holy, holy, holy is Hashem of hosts. (Yeshayahu)',
  'Chassidus: The grass withers, the flower fades; but the word of our G-d stands forever. (Yeshayahu)',
  'Chassidus: Comfort, comfort My people. (Yeshayahu)',
  'Chassidus: A voice calls in the wilderness: Prepare the way of Hashem. (Yeshayahu)',
  'Chassidus: And the glory of Hashem shall be revealed. (Yeshayahu)',
  'Chassidus: The Redeemer will come to Zion. (Yeshayahu)',
  'Chassidus: And from Zion shall go forth the Torah. (Yeshayahu)',
  'Chassidus: Nation shall not lift up sword against nation. (Yeshayahu)',
  'Chassidus: They shall beat their swords into plowshares. (Yeshayahu)',
  'Chassidus: The wolf shall dwell with the lamb. (Yeshayahu)',
  'Chassidus: For the earth shall be full of the knowledge of Hashem. (Yeshayahu)',
  'Chassidus: The righteous shall live by his faith. (Chabakuk)',
  'Chassidus: Hashem is in His holy Temple; let all the earth be silent before Him. (Chabakuk)',
  'Chassidus: Rejoice in Hashem always. (Tehillim)',
  'Chassidus: The L-rd is near to all who call upon Him. (Tehillim)',
  'Chassidus: Open my eyes that I may behold wonders from Your Torah. (Tehillim)',
  'Chassidus: Your word is a lamp to my feet. (Tehillim)',
  'Chassidus: The Torah of Hashem is perfect, restoring the soul. (Tehillim)',
  'Chassidus: The precepts of Hashem are right, rejoicing the heart. (Tehillim)',
  'Chassidus: The commandment of Hashem is pure, enlightening the eyes. (Tehillim)',
  'Chassidus: The fear of Hashem is clean, enduring forever. (Tehillim)',
  'Chassidus: More to be desired are they than gold. (Tehillim)',
  'Chassidus: Sweet also than honey and the honeycomb. (Tehillim)',
  'Chassidus: Moreover by them is Your servant warned. (Tehillim)',
  'Chassidus: In keeping them there is great reward. (Tehillim)',
  'Chassidus: Who can discern errors? Cleanse me from hidden faults. (Tehillim)',
  'Chassidus: Create in me a clean heart, O G-d. (Tehillim)',
  'Chassidus: And renew a steadfast spirit within me. (Tehillim)',
  'Chassidus: Cast me not away from Your presence. (Tehillim)',
  'Chassidus: And take not Your holy spirit from me. (Tehillim)',
  'Chassidus: Restore unto me the joy of Your salvation. (Tehillim)',
  'Chassidus: Then I will teach transgressors Your ways. (Tehillim)',
  'Chassidus: And sinners shall return to You. (Tehillim)',
  'Chassidus: The sacrifices of G-d are a broken spirit. (Tehillim)',
  'Chassidus: A broken and contrite heart, O G-d, You will not despise. (Tehillim)',
  'Chassidus: Make me to know Your ways, O Hashem. (Tehillim)',
  'Chassidus: Teach me Your paths. (Tehillim)',
  'Chassidus: Lead me in Your truth and teach me. (Tehillim)',
  'Chassidus: For You are the G-d of my salvation. (Tehillim)',
  'Chassidus: On You I wait all the day. (Tehillim)',
  'Chassidus: Good and upright is Hashem. (Tehillim)',
  'Chassidus: Therefore He instructs sinners in the way. (Tehillim)',
  'Chassidus: He guides the humble in justice. (Tehillim)',
  'Chassidus: And He teaches the humble His way. (Tehillim)',
  'Chassidus: All the paths of Hashem are mercy and truth. (Tehillim)',
  'Chassidus: For those who keep His covenant and His testimonies. (Tehillim)',
  'Chassidus: The secret of Hashem is with those who fear Him. (Tehillim)',
  'Chassidus: And His covenant to make them know it. (Tehillim)',
  'Chassidus: My eyes are ever toward Hashem. (Tehillim)',
  'Chassidus: For He shall pluck my feet out of the net. (Tehillim)',
  'Chassidus: Turn You unto me and have mercy upon me. (Tehillim)',
  'Chassidus: For I am desolate and afflicted. (Tehillim)',
  'Chassidus: The troubles of my heart are enlarged. (Tehillim)',
  'Chassidus: O bring You me out of my distresses. (Tehillim)',
  'Chassidus: Look upon my affliction and my pain. (Tehillim)',
  'Chassidus: And forgive all my sins. (Tehillim)',
  'Chassidus: Consider my enemies, for they are many. (Tehillim)',
  'Chassidus: O keep my soul and deliver me. (Tehillim)',
  'Chassidus: Let me not be ashamed, for I put my trust in You. (Tehillim)',
  'Chassidus: Let integrity and uprightness preserve me. (Tehillim)',
  'Chassidus: For I wait on You. (Tehillim)',
  'Chassidus: Redeem Israel, O G-d, out of all his troubles. (Tehillim)',
  'Chassidus: Hashem is my rock and my fortress. (Tehillim)',
  'Chassidus: My G-d, my strength, in whom I will trust. (Tehillim)',
  'Chassidus: My shield and the horn of my salvation. (Tehillim)',
  'Chassidus: My high tower. (Tehillim)',
  'Chassidus: I will call upon Hashem, who is worthy to be praised. (Tehillim)',
  'Chassidus: So shall I be saved from my enemies. (Tehillim)',
  'Chassidus: The sorrows of death compassed me. (Tehillim)',
  'Chassidus: In my distress I called upon Hashem. (Tehillim)',
  'Chassidus: And cried to my G-d. (Tehillim)',
  'Chassidus: He heard my voice out of His Temple. (Tehillim)',
  'Chassidus: And my cry came before Him. (Tehillim)',
  'Chassidus: He sent from above, He took me. (Tehillim)',
  'Chassidus: He drew me out of many waters. (Tehillim)',
  'Chassidus: He delivered me from my strong enemy. (Tehillim)',
  'Chassidus: Hashem is my stay. (Tehillim)',
  'Chassidus: He is my refuge and my fortress. (Tehillim)',
  'Chassidus: My G-d, in Him I will trust. (Tehillim)',
];

/** Get one-line parsha summary; pass English parsha name (e.g. "Bereshit"). */
export function getParshaSummary(parshaName: string | undefined): string {
  if (!parshaName) return 'This week\'s Torah portion.';
  const normalized = parshaName.replace(/^Parashat\s+/i, '').trim();
  return PARSHA_SUMMARIES[normalized] || `${parshaName} — see the full parsha in the Library.`;
}
